Repository CodingTrain/website, pull requests merged in 2018-07, with the labels that each got.

#653 Fixing broken downgit URL
  _CodingChallenges/014-fractaltree.md
  _CodingChallenges/015-fractaltreearray.md
  _CodingChallenges/017-spacecolonizer.md
  _CodingChallenges/032.1-agar.md
  _CodingChallenges/038-work-interactor.md
  _CodingChallenges/039-madlibs.md
  _CodingChallenges/040.3-tf-idf.md
  _CodingChallenges/041-clappy-bird.md
  _CodingChallenges/042.1-markov-chains.md
  _CodingChallenges/042.2-markov-chains.md
  _CodingChallenges/045-firebasesavingdrawing.md
  _CodingChallenges/074-clock.md
  _CodingChallenges/090-floyd-steinberg-dithering.md
  _jekyll/layouts/video.html
Labels: Website, bug

#660 add first contribution to mapping coding challenge
  _CodingChallenges/109-subscribers-map.md
Labels: Community Contribution

#661 add javascript implementation
  _CodingChallenges/101-may-the-4th.md
Labels: Community Contribution

#667 Adding 011 Coding Challenge Contribution
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#627 made processing version of CC 16
  CodingChallenges/CC_016_LSystem_Processing/CC_016_LSystem_Processing.pde
Labels: Code Portation (p5.js/Processing)
