Repository CodingTrain/website, pull requests merged in 2018-02, with the labels that each got.

#425 Update 69.4 for contribution
  _CodingChallenges/69.4-steering-evolution.md
Labels: Website, bug

#423 Fixed small visual aspects, reorganized some code, increased readability, and slightly improved loading speed.
  Gemfile.lock
  _CodingChallenges/69.4-steering-evolution.md
  _jekyll/includes/2-base/navigation.html
  _jekyll/includes/3-modules/video-card.html
  assets/css/1-tools/_fonts.sass
  assets/css/1-tools/_vars.sass
  assets/css/2-base/_ctas.sass
  assets/css/2-base/_footer.sass
  assets/css/2-base/_landing-page.sass
  assets/css/2-base/_navigation.sass
  assets/css/2-base/_typeface.sass
  assets/css/4-modules/_video-card.sass
  assets/images/header.jpg
  assets/images/streamcover.jpg
  assets/javascript/functions.js
Labels: Website

#432 Livestream #116.1
  _Streams/116.1-Snakes-and-Ladders.md
Labels: Website

#422 Adding a contribution
  _CodingChallenges/69.4-steering-evolution.md
Labels: Community Contribution

#448 Update CC_17_SpaceColonizer.pde
  CodingChallenges/CC_17_SpaceColonizer/CC_17_SpaceColonizer.pde
Labels: Enhancement, bug

#451 Updated README
  README.md
Labels: Website

#450 Add contribution to #93
  _CodingChallenges/93-double-pendulum.md
Labels: Community Contribution

#426 Added community contribution
  _CodingChallenges/30-phyllotaxis.md
Labels: Community Contribution

#456 My contribution to Fractal Tree Conding Challenge
  _CodingChallenges/14-fractaltree.md
Labels: Community Contribution

#431 Livestream #116.2
  _Streams/116-walks.md
  _Streams/116.2-snakes-ladders-continued-2048.md
Labels: Website

#433 Livestream #115
  _Streams/115-backpropagation.md
Labels: Website

#435 Livestream #118 update
  _Streams/118-more-neural-networks.md
Labels: Website

#436 Livestream #119 update
  _Streams/119-solving-merge-conflicts-xor-problem.md
Labels: Website

#439 Livestream #114.2
  _Streams/114.2-revisiting-feedforward-algorithm.md
Labels: Website

#453 Update 71-minesweeper.md
  _CodingChallenges/71-minesweeper.md
Labels: Community Contribution

#452 Update 03-snake-game-p5.md
  _CodingChallenges/03-snake-game-p5.md
Labels: Community Contribution

#457 Update sketch.js
  CodingChallenges/CC_94_2048/sketch.js
Labels: Enhancement

#460 Added link to github in the header
  _jekyll/includes/2-base/navigation.html
Labels: Website

#442 Livestream #114.1 - Fixed
  _Streams/114.1-neural-networks-continued.md
Labels: Website

#473 Update 51.2-astar.md
  _CodingChallenges/51.2-astar.md
Labels: Community Contribution

#472 Challenge 74-clock Community contribution
  _CodingChallenges/74-clock.md
Labels: Community Contribution

#469 Sakura tree blossoms
  _CodingChallenges/17-spacecolonizer.md
Labels: Community Contribution

#468 Adding my version of the maze generator
  _CodingChallenges/10.4-maze-dfs-p5.md
Labels: Community Contribution

#454 Livestream #112
  _Streams/112-happy-holidays.md
Labels: Website

#434 Livestream #117.2
  _Streams/117.2-unit-testing-ci-circleci.md
Labels: Website

#476 Adding my own version of the Evolutionary Steering Simulation
  _CodingChallenges/69.4-steering-evolution.md
Labels: Community Contribution

#445 Livestream #113
  _Streams/113-return-neural-networks.md
Labels: Website

#484 2048 Contribution - C# + Discord BOT
  _CodingChallenges/94.1-2048.md
Labels: Community Contribution
