Repository CodingTrain/website, pull requests merged in 2018-03, with the labels that each got.

#489 Update 93-double-pendulum.md
  _CodingChallenges/93-double-pendulum.md
Labels: Community Contribution

#488 Please add my custom version of 2048
  _CodingChallenges/94.3-2048.md
Labels: Community Contribution

#494 Fixed incorrect video id
  _Tutorials/16-javascript-es6/16.7-reduce.md
Labels: Website

#490 adding contribution of the game MineSweeper
  _CodingChallenges/71-minesweeper.md
Labels: Community Contribution

#491 Add my contribution
  _CodingChallenges/94.1-2048.md
Labels: Community Contribution

#492 Add contribution to #51
  _CodingChallenges/51.1-astar.md
Labels: Community Contribution

#493 Added unit testing with jest and continuous development with circle ci.
  .circleci/config.yml
  _CodingChallenges/81.2-circle-morphing-part-2.md
  _CodingChallenges/93-double-pendulum.md
  unit_testing/coding-challange-yaml.test.js
  unit_testing/package-lock.json
  unit_testing/package.json
  unit_testing/readme.md
Labels: Website

#500 Added a notice to include a URL to the running example in a PRs description in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Enhancement

#497 Adding my own version of the XOR Problem
  _CodingChallenges/92-xor.md
Labels: Community Contribution

#504 Added Learning-Processing Course and fixed the "series within series" problem #499
  CNAME
  _Courses/learning-processing/0-introduction/0.0-introduction.md
  _Courses/learning-processing/0-introduction/0.1-who-are-you-who-am-i.md
  _Courses/learning-processing/0-introduction/0.2-why-learn-processing.md
  _Courses/learning-processing/0-introduction/0.3-what-is-programming.md
  _Courses/learning-processing/0-introduction/0.4-what-programming-lang.md
  _Courses/learning-processing/0-introduction/0.5-processing-examples.md
  _Courses/learning-processing/0-introduction/0.6-overview-topics.md
  _Courses/learning-processing/0-introduction/index.md
  _Courses/learning-processing/index.md
  _jekyll/layouts/series-index.html
Labels: Website

#501 Test YAML with PropTypes
  .circleci/config.yml
  _Courses/programming-with-text/10-chatbots/10.2-rivescript.md
  _Courses/programming-with-text/11-chrome-extensions/11.1-introduction.md
  _Courses/programming-with-text/11-chrome-extensions/11.5-pop-ups.md
  _Courses/programming-with-text/2-regular-expressions/2.1-introduction.md
  _Courses/programming-with-text/2-regular-expressions/2.10-homework-assignments.md
  _Courses/programming-with-text/2-regular-expressions/2.2-meta-characters.md
  _Courses/programming-with-text/2-regular-expressions/2.3-character-classes.md
  _Courses/programming-with-text/2-regular-expressions/2.4-capturing-groups.md
  _Courses/programming-with-text/2-regular-expressions/2.5-back-references.md
  _GuestTutorials/6-golan-levin-modulo-operator.md
  _GuestTutorials/7-golan-levin-circle-morphing.md
  _Streams/106.1-chrome-extensions-part-1.md
  _Streams/106.2-chrome-extensions-part-2.md
  _Streams/108-nn-continued.md
  _Streams/110-webgl-with-p5js-continued.md
  _Streams/124-upcoming.md
  unit_testing/coding-challange-yaml.test.js
  unit_testing/formats.js
  unit_testing/package-lock.json
  unit_testing/package.json
  unit_testing/yaml.test.js
Labels: Website

#416 Added Stream #111
  _Streams/111-more-webgl-with-p5js.md
  _Tutorials/18-webgl/18.6-create-graphics-as-webgl-texture.md
  _Tutorials/18-webgl/18.7-loading-obj-model.md
  _Tutorials/18-webgl/18.8-custom-shapes-in-webgl-with-p5js.md
  _Tutorials/9-additional-topics/9.22-custom-shapes.md
  _Tutorials/9-additional-topics/9.23-create-graphics.md
Labels: Website

#512 Update 93-double-pendulum.md
  _CodingChallenges/93-double-pendulum.md
Labels: Community Contribution

#510 CC_94_2048: Removed unnecessary direction in transposeGrid
  CodingChallenges/CC_94_2048/grid.js
  CodingChallenges/CC_94_2048/sketch.js
Labels: Enhancement

#517 Created remaining "Higher Order Functions"-pages
  _Tutorials/16-javascript-es6/16.10-particle-system-with-js-array-functions.md
  _Tutorials/16-javascript-es6/16.8-filter.md
  _Tutorials/16-javascript-es6/16.9-sort.md
Labels: Website

#511 Multi-part videos should only allow contributions to the first part
  _jekyll/layouts/video.html
Labels: Website

#518 Enforce multi part contributions restrictions
  _CodingChallenges/10.1-maze-dfs-p5.md
  _CodingChallenges/10.4-maze-dfs-p5.md
  _CodingChallenges/46.2-asteroids-part-2.md
  _CodingChallenges/51.1-astar.md
  _CodingChallenges/51.2-astar.md
  _CodingChallenges/69.1-steering-evolution.md
  _CodingChallenges/69.4-steering-evolution.md
  _CodingChallenges/94.1-2048.md
  _CodingChallenges/94.3-2048.md
  unit_testing/yaml.test.js
Labels: Website

#477 Adding my own version of this Coding Challenge
  CodingChallenges/CC_69_steering_evolution/README.md
Labels: Community Contribution
