Repository CodingTrain/website, pull requests merged in 2018-12, with the labels that each got.

#875 Added Node.js as a code variation
  CodingChallenges/CC_032.2_agar.io_sockets/Node/package.json
  CodingChallenges/CC_032.2_agar.io_sockets/Node/public/blob.js
  CodingChallenges/CC_032.2_agar.io_sockets/Node/public/index.html
  CodingChallenges/CC_032.2_agar.io_sockets/Node/public/sketch.js
  CodingChallenges/CC_032.2_agar.io_sockets/Node/server.js
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/.env-sample
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/.gitignore
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/bot.js
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/package-lock.json
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/package.json
  CodingChallenges/CC_118_Mastodon_TreeBot/Node/treegen/treegen.pde
  CodingChallenges/CC_122_QuickDraw/Node/package.json
  CodingChallenges/CC_122_QuickDraw/Node/public/index.html
  CodingChallenges/CC_122_QuickDraw/Node/public/sketch.js
  CodingChallenges/CC_122_QuickDraw/Node/server.js
  _config.yml
Labels: Code Portation (p5.js/Processing), Website

#911 Update 125-fourier-series.md
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#912 CC115 Code + Processing Port
  CodingChallenges/CC_115_Snake_Game_Redux/P5/index.html
  CodingChallenges/CC_115_Snake_Game_Redux/P5/sketch.js
  CodingChallenges/CC_115_Snake_Game_Redux/P5/snake.js
  CodingChallenges/CC_115_Snake_Game_Redux/Processing/Snake_Game_Redux/Snake_Game_Redux.pde
  CodingChallenges/CC_115_Snake_Game_Redux/Processing/Snake_Game_Redux/snake.pde
  _CodingChallenges/115-snake-game-redux.md
Labels: Code Portation (p5.js/Processing)

#914 Added target="_blank" to code-variation-dropdown.html
  _jekyll/includes/3-modules/code-variation-dropdown.html
Labels: Website

#915 Port of CC120 to p5
  CodingChallenges/CC_120_Bit_Shifting/P5/bit.js
  CodingChallenges/CC_120_Bit_Shifting/P5/index.html
  CodingChallenges/CC_120_Bit_Shifting/P5/sketch.js
  _CodingChallenges/120-bit-shifting.md
Labels: Code Portation (p5.js/Processing)

#916 Update 125-fourier-series.md
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#921 Added my C++ implementation of the Barnsley Fern
  _CodingChallenges/108-barnsley-fern.md
Labels: Community Contribution

#923 Rainbow Fourier seres: Sawtooth
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#924 Port of CC125 to Processing
  CodingChallenges/CC_125_Fourier_Series/Processing/CC_125_Fourier_Series/CC_125_Fourier_Series.pde
Labels: Code Portation (p5.js/Processing)

#926 Added Contribution
  _CodingChallenges/126-toothpicks.md
Labels: Community Contribution

#927 p5 Version of CC119
  CodingChallenges/CC_119_Binary_to_Decimal_Conversion/P5/bit.js
  CodingChallenges/CC_119_Binary_to_Decimal_Conversion/P5/index.html
  CodingChallenges/CC_119_Binary_to_Decimal_Conversion/P5/sketch.js
  _CodingChallenges/119-binary-decimal-conversion.md
Labels: Code Portation (p5.js/Processing)

#925 Transcribe Lissajous to javascript.
  CodingChallenges/CC_116_Lissajous/P5/curve.js
  CodingChallenges/CC_116_Lissajous/P5/index.html
  CodingChallenges/CC_116_Lissajous/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#931 Web editor Version for CC121.1 & CC121.2
  CodingChallenges/CC_121_Logo_1/P5/sketch.js
  CodingChallenges/CC_121_Logo_1/P5/turtle.js
  CodingChallenges/CC_121_Logo_2/P5/command.js
  CodingChallenges/CC_121_Logo_2/P5/parser.js
  CodingChallenges/CC_121_Logo_2/P5/sketch.js
  CodingChallenges/CC_121_Logo_2/P5/turtle.js
  _CodingChallenges/121.1-logo-interpreter.md
  _CodingChallenges/121.2-logo-interpreter.md
Labels: Code Portation (p5.js/Processing)

#930 Transcribe Hypercube to javascript.
  CodingChallenges/CC_113_Hypercube/P5/P4Vector.js
  CodingChallenges/CC_113_Hypercube/P5/index.html
  CodingChallenges/CC_113_Hypercube/P5/matrix.js
  CodingChallenges/CC_113_Hypercube/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#932 Enforce Web Editor existence, user & mapping to repositories
  unit_testing/package-lock.json
  unit_testing/package.json
  unit_testing/yaml.test.js
Labels: Website

#891 WaterRipple Update
  _CodingChallenges/102-2d-water-ripple.md
Labels: Community Contribution

#727 Add a contribution for Snake CC
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#703 Update 114-bubble-sort.md
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#693 Update 108-barnsley-fern.md
  _CodingChallenges/108-barnsley-fern.md
Labels: Community Contribution

#692 Updated with my contribution
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#935 Testing: Repositories must exist
  CodingChallenges/CC_110.2_recaman_music/P5/index.html
  CodingChallenges/CC_110.2_recaman_music/P5/sketch.js
  _CodingChallenges/006-mitosis-p5.md
  _CodingChallenges/097.1-book-of-pi.md
  _Courses/programming-with-text/10-chatbots/10.3-text-to-speech.md
  _Courses/programming-with-text/10-chatbots/10.4-speech-recognition.md
  _Courses/programming-with-text/11-chrome-extensions/11.2-bookmarklets.md
  _Courses/programming-with-text/11-chrome-extensions/11.3-content-scripts.md
  _Courses/programming-with-text/11-chrome-extensions/11.4-background-scripts.md
  _Courses/programming-with-text/11-chrome-extensions/11.6-pop-ups-messaging.md
  _Courses/programming-with-text/11-chrome-extensions/11.7-new-tab-override.md
  _Courses/programming-with-text/11-chrome-extensions/11.8-cross-browser-extensions.md
  _Courses/programming-with-text/2-regular-expressions/2.6-test-and-match.md
  _Courses/programming-with-text/2-regular-expressions/2.7-exec.md
  _Courses/programming-with-text/2-regular-expressions/2.8-split.md
  _Courses/programming-with-text/2-regular-expressions/2.9-replace.md
  _Tutorials/10-working-with-data/10.10-giphy-api.md
  _Tutorials/10-working-with-data/10.2-what-is-json-part-1.md
  _Tutorials/10-working-with-data/10.3-what-is-json-part-2.md
  _Tutorials/10-working-with-data/10.6-api-query-with-user-input.md
  _Tutorials/12-websockets/12.1-introduction-to-node.md
  _Tutorials/12-websockets/12.2-using-express-with-node.md
  _Tutorials/12-websockets/12.3-socket-io.md
  _Tutorials/12-websockets/12.4-shared-drawing-canvas.md
  _Tutorials/16-javascript-es6/16.3-arrow-function.md
  _Tutorials/18-webgl/18.1-introduction-to-webgl.md
  _Tutorials/18-webgl/18.2-3d-geometries.md
  _Tutorials/18-webgl/18.3-light-and-material.md
  _Tutorials/18-webgl/18.4-textures.md
  _Tutorials/18-webgl/18.6-create-graphics-as-webgl-texture.md
  _Tutorials/18-webgl/18.7-loading-obj-model.md
  _Tutorials/18-webgl/18.8-custom-shapes-in-webgl-with-p5js.md
  _Tutorials/7-object-interaction/7.4-mouse-interaction.md
  _Tutorials/7-object-interaction/7.5-removing-objects-from-array.md
  _Tutorials/7-object-interaction/7.6-object-communication-part-1.md
  _Tutorials/7-object-interaction/7.7-object-communication-part-2.md
  _Tutorials/7-object-interaction/7.8-objects-and-images.md
  _Tutorials/8-html-css-dom/8.1-what-is-html.md
  _Tutorials/8-html-css-dom/8.10-select-and-selectall.md
  _Tutorials/8-html-css-dom/8.11-callbacks-on-multiple-dom-elements.md
  _Tutorials/8-html-css-dom/8.12-parent-and-child.md
  _Tutorials/8-html-css-dom/8.13-assigning-css-class-dynamically.md
  _Tutorials/8-html-css-dom/8.14-parent-and-child-with-variables.md
  _Tutorials/8-html-css-dom/8.15-drag-and-drop.md
  _Tutorials/8-html-css-dom/8.16-slider-dance.md
  _Tutorials/8-html-css-dom/8.2-creating-html-elements.md
  _Tutorials/8-html-css-dom/8.3-manipulating-dom-elements.md
  _Tutorials/8-html-css-dom/8.4-handling-dom-events.md
  _Tutorials/8-html-css-dom/8.5-interacting-with-the-dom.md
  _Tutorials/8-html-css-dom/8.6-other-events-and-inputs.md
  _Tutorials/8-html-css-dom/8.7-css-basics.md
  _Tutorials/8-html-css-dom/8.8-events-changed-and-input.md
  _Tutorials/8-html-css-dom/8.9-css-selectors.md
  _Tutorials/9-additional-topics/9.20-polar-coordinates.md
  _Tutorials/9-additional-topics/9.22-custom-shapes.md
  _Tutorials/9-additional-topics/9.23-create-graphics.md
  unit_testing/formats.js
  unit_testing/helpers.js
  unit_testing/yaml.test.js
Labels: Website

#941 Added contribution.
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#953 New contribution
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#950 Add Optimized Brownian Snowflake in Processing
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#957 ES6 Brownian Snowflake
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#958 New contribution
  _CodingChallenges/129-koch-snowflake.md
Labels: Community Contribution

#960 Added contribution to 129-koch-snowflake.md
  _CodingChallenges/129-koch-snowflake.md
Labels: Community Contribution

#940 Transcribe Logo_1 to Processing.
  CodingChallenges/CC_121_Logo_1/Processing/CC_121_Logo_1/CC_121_Logo_1.pde
  CodingChallenges/CC_121_Logo_1/Processing/CC_121_Logo_1/Turtle.pde
  CodingChallenges/CC_121_Logo_1/Processing/CC_121_Logo_1/code.txt
Labels: Code Portation (p5.js/Processing)
