Repository CodingTrain/website, pull requests merged in 2018-10, with the labels that each got.

#725 Fix KO url contribution
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution, bug

#733 Added View Code buttons to Tutorials
  _config.yml
  _jekyll/layouts/video.html
  assets/css/3-layouts/_video.sass
Labels: Website

#748 add missing space before (Java)
  _CodingChallenges/114-bubble-sort.md
Labels: Website, bug

#754 Another Lissajous Table contribution
  _CodingChallenges/116-lissajous.md
Labels: Community Contribution

#756 Community Contribution CC #115
  _CodingChallenges/114-bubble-sort.md
  _CodingChallenges/115-snake-game-redux.md
Labels: Community Contribution

#751 Fixed Gemfile Vulnerabilities
  Gemfile.lock
Labels: Website, bug

#718 Added Contribution
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#747 Add web editor to video page
  _CodingChallenges/115-snake-game-redux.md
  _CodingChallenges/116-lissajous.md
  _config.yml
  _jekyll/layouts/video.html
  unit_testing/formats.js
Labels: Website

#782 Added new banner
  assets/images/header.jpg
Labels: Website

#781 Community Contribution
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#521 Update content.js
  CodingChallenges/CC_84_Word_Definition_Extension/content.js
Labels: Enhancement

#787 Community Contribution: Game of Life in p5 with editable grid
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#552 Added quadTree (Part 1) and (Part 2) separate in Processing and renamed quadTree.js
  CodingChallenges/CC_098_1_QuadTree_Processing/CC_098_1_QuadTree_Processing.pde
  CodingChallenges/CC_098_1_QuadTree_Processing/Point.pde
  CodingChallenges/CC_098_1_QuadTree_Processing/Rectangle.pde
  CodingChallenges/CC_098_1_QuadTree_Processing/quadtree.pde
  CodingChallenges/CC_098_3_QuadTree_Collisions_Processing/CC_098_3_QuadTree_Collisions_Processing.pde
  CodingChallenges/CC_098_3_QuadTree_Collisions_Processing/Point.pde
  CodingChallenges/CC_098_3_QuadTree_Collisions_Processing/Rectangle.pde
  CodingChallenges/CC_098_3_QuadTree_Collisions_Processing/quadtree.pde
Labels: Code Portation (p5.js/Processing)

#626 Converted CC_014 to processing
  CodingChallenges/CC_014_FractalTree_Processing/CC_014_FractalTree_Processing.pde
Labels: Code Portation (p5.js/Processing)

#642 Cc 035 ported to processing
  CodingChallenges/CC_035_TSP_Processing/CC_35_1_TSP/CC_35_1_TSP.pde
  CodingChallenges/CC_035_TSP_Processing/CC_35_2_LexicographicOrder/CC_35_2_LexicographicOrder.pde
  CodingChallenges/CC_035_TSP_Processing/CC_35_3_TSP_Lexical/CC_35_3_TSP_Lexical.pde
  CodingChallenges/CC_035_TSP_Processing/CC_35_4_TSP_GA/CC_35_4_TSP_GA.pde
  CodingChallenges/CC_035_TSP_Processing/CC_35_4_TSP_GA/ga.pde
Labels: Code Portation (p5.js/Processing)

#645 Add port to p5.js of coding challenge 107 (sandpiles)
  CodingChallenges/CC_107_sandpiles_p5.js/index.html
  CodingChallenges/CC_107_sandpiles_p5.js/sketch.js
Labels: Code Portation (p5.js/Processing)

#696 3D rendering in the console
  _CodingChallenges/112-3d-rendering.md
Labels: Community Contribution

#722 Switch from let to const
  Tutorials/P5JS/16_promises/13_16_async_await/sketch.js
Labels: Enhancement

#556 Adding safety-check to prevent "points no iterable" error
  CodingChallenges/CC_098_1_QuadTree/sketch.js
Labels: Enhancement

#549 Fixed `contains(point)` range checking
  CodingChallenges/CC_098_1_QuadTree/quadtree.js
Labels: Enhancement

#793 Added the "lang" attribute on "html" for accessibility reasons (#792)
  _jekyll/layouts/base.html
Labels: Website, accessibility

#794 Port of CC36 from p5 to Processing
  CodingChallenges/CC_036_Blobby/CC_036_Blobby.pde
  CodingChallenges/CC_036_Blobby_p5.js/index.html
  CodingChallenges/CC_036_Blobby_p5.js/sketch.js
  _CodingChallenges/036-blobby.md
Labels: Code Portation (p5.js/Processing)

#798 Fix #788 - Update username
  _CodingChallenges/105-polynomial-regression-tfjs.md
Labels: Community Contribution, bug

#803 Add contribution to the Lissajous CC
  _CodingChallenges/116-lissajous.md
Labels: Community Contribution

#810 Update 022-juliaset.md
  _CodingChallenges/022-juliaset.md
Labels: Community Contribution

#811 Add my 7-segment display contribution
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#823 Replaced the old merch store image with the new DBH
  assets/images/merch-store.png
Labels: Website

#829 challenge 121 logo code
  CodingChallenges/CC_121_Logo/P5/index.html
  CodingChallenges/CC_121_Logo/P5/sketch.js
  CodingChallenges/CC_121_Logo/P5/turtle.js
  _CodingChallenges/121-logo-interpreter.md
Labels: Missing code

#832 Contribution To Logo Interpreter Coding Challenge #121
  _CodingChallenges/121-logo-interpreter.md
Labels: Community Contribution
