Repository CodingTrain/website, pull requests merged in 2019-11, with the labels that each got.

#1534 improved error logging
  unit_testing/files.js
  unit_testing/yaml.test.js
Labels: CI

#1880 Update 148-gift-wrapping.md
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1886 Adding caching
  .github/workflows/nodejs.yml
  .github/workflows/ruby.yml
Labels: CI

#1881 rearranged footer links
  _jekyll/includes/2-base/footer.html
Labels: Website

#1892 Create gist.yml
  .github/workflows/gist.yml
Labels: CI

#1883 Updating support section from patron to member
  _jekyll/includes/4-vector-graphics/squarebrackets.svg
  landing-page.html
Labels: Website

#1900 Added contribution to teachable machine game
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1902 Maurer rose contribution: make rose rainbow color
  _CodingInTheCabana/001-maurer-rose.md
Labels: Community Contribution

#1744 darken the navbar on hover (with a smooth transition)
  assets/css/2-base/_navigation.sass
Labels: Website

#1908 Update 2-teachable-game.md
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1909 Update 002-collatz-conjecture.md
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1913 Added Contribution
  _TeachableMachine/3-teachable-audio.md
Labels: Community Contribution

#1921 Add Brownian Tree Snowflake falling animation w/p5
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#1928 Polar Rose Fireworks
  _CodingChallenges/055-roses.md
Labels: Community Contribution

#1929 configuring eslint for ci testing
  .eslintignore
  .eslintrc.js
  .github/workflows/nodejs.yml
  CodingChallenges/CC_034_DLA/P5/walker.js
  CodingChallenges/CC_068_BFS_kevin_bacon/P5/sketch.js
  CodingChallenges/CC_089_langtonsant/P5/sketch.js
  CodingChallenges/CC_121_Logo_2/P5/parser.js
  Courses/programming_with_text/session04/deprecated_twitter_bots/node3/bot.js
  Courses/programming_with_text/session04/deprecated_twitter_bots/node4_a_setInterval/bot.js
  Courses/programming_with_text/session04/deprecated_twitter_bots/node4_b_followbot/bot.js
  Courses/programming_with_text/session04/deprecated_twitter_bots/node5/bot.js
  Courses/programming_with_text/session08/8-0506_SavingDataJSONnodeJS/server.js
  Courses/programming_with_text/session08/8-07_ConclusionHTTPPOST/server.js
  Tutorials/P5JS/p5.js/08/8.02_p5.js_Creating_HTML_elements_with_JavaScript/sketch.js
  package.json
Labels: CI, Website

#1944 Adding my version of ml5 network
  _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Labels: Community Contribution

#1945 Contribution for Coding Challenge 64
  _CodingChallenges/064.1-forward-kinematics.md
Labels: Community Contribution

#1946 ml5-train-your-own contribution: regression added
  _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Labels: Community Contribution

#1950 Snake Game Evolutionary AI
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1951 Update 2-teachable-game.md
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1954 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#1955 train your own NN: learn different colors
  _Courses/ml5-beginners-guide/6.1-ml5-train-your-own.md
Labels: Community Contribution
