Repository CodingTrain/website, pull requests merged in 2019-04, with the labels that each got.

#1241 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#1253 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1249 Update 143-quicksort.md
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#1258 Add my CC 143 contribution
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#1250 Update 030-phyllotaxis.md
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#1259 Adding my contribution in Mandelbort set
  _CodingChallenges/141-mandelbrot-pi.md
Labels: Community Contribution

#1263 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1080 Add p5js basics section 2
  _Tutorials/2-variables/2.1-mousex-mousey.md
  _Tutorials/2-variables/2.2-make-your-own.md
  _Tutorials/2-variables/2.3-objects.md
  _Tutorials/2-variables/2.4-map.md
  _Tutorials/2-variables/2.5-random.md
  _Tutorials/2-variables/index.md
Labels: Website

#1081 Added section 3 of p5js tutorials
  _Tutorials/3-conditionals/3.1-introduction.md
  _Tutorials/3-conditionals/3.2-bouncing-ball.md
  _Tutorials/3-conditionals/3.3-else-elseif-and-or.md
  _Tutorials/3-conditionals/3.4-boolean-variables.md
  _Tutorials/3-conditionals/index.md
Labels: Website

#1084 Create p5js tutorials section 6
  _Tutorials/6-objects/6.1-introduction.md
  _Tutorials/6-objects/index.md
Labels: Website

#1083 Create p5js tutorials section 5
  _Tutorials/5-functions/5.1-basics.md
  _Tutorials/5-functions/5.2-parameters-arguments.md
  _Tutorials/5-functions/5.3-return.md
  _Tutorials/5-functions/index.md
Labels: Website

#1082 Add p5js tutorial section 4
  _Tutorials/4-loops/4.1-while-for
  _Tutorials/4-loops/4.2-nested-loops
  _Tutorials/4-loops/index.md
Labels: Website

#1264 Fixing series index
  _Tutorials/5-functions/index.md
Labels: Fix, Website

#1265 Update 139-pi-collisions.md
  _CodingChallenges/139-pi-collisions.md
Labels: Community Contribution

#1266 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1267 Adding the dotenv Gem
  Gemfile
  Gemfile.lock
Labels: Repository

#1268 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1269 Added my contribution
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1270 Update 116-lissajous.md with gui-santos version of the challenge
  _CodingChallenges/116-lissajous.md
Labels: Community Contribution

#1272 Update 134.1-heart-curve.md
  _CodingChallenges/134.1-heart-curve.md
Labels: Community Contribution

#1277 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1279 Fouries Series Audiovisualisation Contribution
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#1281 Update node deps and fixing 2 vulnerabilities
  package-lock.json
  package.json
Labels: Fix, Repository

#1286 Add my sketch
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#1285 Adding repo for 142 part 3
  _CodingChallenges/142.3-rubiks-cube.md
Labels: Repository

#1287 Update 087-3Dknots.md
  _CodingChallenges/087-3Dknots.md
Labels: Community Contribution

#1289 Update 076-10print.md
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#1291 Update 034-dla.md
  _CodingChallenges/034-dla.md
Labels: Community Contribution

#1293 Update 142.1-rubiks-cube.md
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1299 Added Contribution To CC 144: FlockingBlackHole
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1298 Update 144-black-hole-visualization.md; Photon orbits around a black hole
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1302 Added contribution: 3D Black Hole in Processing
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1303 VulcanoGame
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1304 added my own live rendering mandelbro explorer
  _CodingChallenges/021-mandelbrot-p5.md
Labels: Community Contribution
