Repository CodingTrain/website, pull requests merged in 2019-07, with the labels that each got.

#1444 Random walk contribution: Visualizing Pi
  _CodingChallenges/052-random-walk.md
Labels: Community Contribution

#1445 Contribution added
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#1446 Added my implementation of coding challenge
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#1448 Update 031-flappybird.md
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#1449 Update 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1451 new contribution
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#1452 comments are added
  CodingChallenges/CC_093_DoublePendulum/Processing/CC_093_DoublePendulum/CC_093_DoublePendulum.pde
Labels: Enhancement

#1454 Update 3.5-deployment.md
  _Courses/data-and-apis/3.5-deployment.md
Labels: Community Contribution

#1455 Add personal contribution to Flappy Bird Coding Challenge
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#1461 Adding Processing Version of CC148
  CodingChallenges/CC_148_Gift_Wrapping/Processing/CC_148_Gift_Wrapping/CC_148_Gift_Wrapping.pde
  CodingChallenges/CC_148_Gift_Wrapping/Processing/CC_148_Gift_Wrapping/sorting.pde
Labels: Code Portation (p5.js/Processing)

#1467 Add contribution.
  _CodingChallenges/065.1-binary-tree.md
Labels: Community Contribution

#1468 Add my python implementation
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#1469 Jarvis March Contribution - CC 148
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1471 Added 2 contributions
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1481 TicTacToe Contribution: human vs human, (click)
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1484 Tic Tac Toe Animated
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1486 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1487 Adding Snake
  _CodingChallenges/115-snake-game-redux.md
Labels: Community Contribution

#1490 Re-sizable Tic-Tac-Toe Human vs Human (click)
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1491 added my version
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1498 Minesweeper Contribution: data oriented approach
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#1489 Adding my version of the coding challenge
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1499 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1497 Tic-Tac-Toe Contribution: Colors instead of XO's
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1493 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1492 CC149 Processing Port
  CodingChallenges/CC_149_Tic_Tac_Toe/Processing/CC_149_Tic_Tac_Toe/CC_149_Tic_Tac_Toe.pde
Labels: Code Portation (p5.js/Processing)

#1495 Coding Challenge #149 Contribution H vs C
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1500 Tic-Tac-Toe Contribution: 2 players (simple)
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1503 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1504 Ported the double pendulum to Processing.py
  _CodingChallenges/093-double-pendulum.md
Labels: Community Contribution

#1505 tic-tac-toe player vs ai
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1511 Added a Hexagon-based version of Minesweeper
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#1509 Add community contribution 10Print variation
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#1508 Fourier Series Contribution: vanilla JS with SVg
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#1512 Refactored the code, reduced to 41LOC.
  _CodingChallenges/116-lissajous.md
Labels: Community Contribution

#1514 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#1515 149tictactoe contrubition: basic & without p5.dom
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1521 Maze Generator: hexagons instead of squares
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#1522 My own contribution adding a skybox to the system
  _CodingChallenges/009-solarsystemgenerator3d-texture.md
Labels: Community Contribution

#1524 switch see it live to live demo
  _jekyll/layouts/video.html
Labels: Website

#1526 all-the-feels contribution
  _CodingChallenges/081.1-circle-morphing-part-1.md
Labels: Community Contribution

#1525 Pure Javascript Implementation with better aesthetics and Slider
  _CodingChallenges/093-double-pendulum.md
Labels: Community Contribution

#1530 My contribution for this challenge
  _CodingChallenges/141-mandelbrot-pi.md
Labels: Community Contribution

#1531 My contribution for this challenge
  _CodingChallenges/110.1-recaman-sequence.md
Labels: Community Contribution

#1532 Lorenz attracto contribution
  _CodingChallenges/012-lorenzattractor.md
Labels: Community Contribution

#1533 My last contribution for today
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#1535 Adding my Version of the TicTacToe
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1536 Update 092-xor.md
  _CodingChallenges/092-xor.md
Labels: Community Contribution

#1523 Moving the Wiki to own Markdown files
  _Guides/community-contribution-guide.md
  _Guides/content-contribution-guide.md
  _Guides/core-contribution-guide.md
  _Guides/index.md
  _config.yml
  _jekyll/includes/2-base/head.html
  _jekyll/layouts/guide.html
  _jekyll/layouts/video.html
  assets/css/1-tools/_syntax-highlighting.scss
  assets/css/1-tools/_vars.sass
  assets/css/2-base/_typeface.sass
  assets/css/3-layouts/_guide.sass
  assets/css/main.sass
  docker-compose.yml
Labels: Repository

#1540 Chrome Dino: responsive jump height/obstacle speed
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#1541 Suncircle styling
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1542 Count Up and Down Timers
  _CodingChallenges/066-timer.md
Labels: Community Contribution

#1557 My Vue Implementation
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1556 Families of 3d knots in p5.js
  _CodingChallenges/087-3Dknots.md
Labels: Community Contribution

#1555 Adding my contribution Mandelbrot set explorer
  _CodingChallenges/021-mandelbrot-p5.md
Labels: Community Contribution

#1554 Pong contribution - with ai
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#1553 p5.js Word Cloud Generator
  _CodingChallenges/040.1-wordcounts-p5.md
Labels: Community Contribution

#1551 Smart Rockets in Logo
  _CodingChallenges/029-smartrockets.md
Labels: Community Contribution

#1543 add Sprite Asteroids version
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#1558 snake contribution: teleporting wall
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#1513 Fixed toolbar (no it wasnt broken ^^)
  DEVELOPING.md
  assets/css/2-base/_navigation.sass
Labels: Enhancement, Website

#1560 Graham Scan Algorithm Implemented
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1562 3D Tic Tac Toe
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1564 Added 10PRINT with a maze crawler function
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#1566 Add Contribution to Polar Perlin Noise Loops
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1568 Space-Invaders Contribution - nothing special
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution

#1567 Working on an AI that's EMOJIonal
  _CodingChallenges/044.1-afinn111sentimentanalysis.md
Labels: Community Contribution

#1570 Simple Analog Clock With Hour And Minute Smoothing
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#1571 149-TicTacToe contribution: 3 in a row from tic tac toe
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1572 added my contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1573 TSP with 2-opt
  _CodingChallenges/035.1-tsp.md
Labels: Community Contribution

#1574 Add community contribution
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1576 Flocking simplex-noise knot creatures
  _CodingChallenges/137-4d-opensimplex-noise-loop.md
Labels: Community Contribution

#1577 Simple Particle System Contribution: Color Smoke
  _CodingChallenges/078-simple-particle-system.md
Labels: Community Contribution

#1578 OU vs. Texas College Football Version
  _CodingChallenges/138-angry-birds.md
Labels: Community Contribution

#1581 Added Fallingnumbers Flee From Mouse
  _CodingChallenges/059-steering-text-paths.md
Labels: Community Contribution

#1583 Just some shapes
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1585 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1586 Raycasting contribution: Self driving robot
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution
