Repository CodingTrain/website, pull requests merged in 2019-05, with the labels that each got.

#1301 Update 144-black-hole-visualization.md with Contribution
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1306 Added my own contribution
  _CodingChallenges/089-langtonsant.md
Labels: Community Contribution

#1307 Update 144-black-hole-visualization.md
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1308 CC 144 Processing Port
  CodingChallenges/CC_144_Black_Hole_Newtonian/Processing/CC_114_Black_Hole_Newtonian/CC_114_Black_Hole_Newtonian.pde
  CodingChallenges/CC_144_Black_Hole_Newtonian/Processing/CC_114_Black_Hole_Newtonian/blackhole.pde
  CodingChallenges/CC_144_Black_Hole_Newtonian/Processing/CC_114_Black_Hole_Newtonian/photon.pde
Labels: Code Portation (p5.js/Processing)

#1305 darken some colors to meet WCAG AA
  assets/css/1-tools/_vars.sass
  assets/css/2-base/_ctas.sass
  assets/css/2-base/_footer.sass
  assets/css/2-base/_landing-page.sass
  assets/css/2-base/_navigation.sass
Labels: Website, accessibility

#1045 Adding Python version of purple rain
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#1046 Adding python version of starfield
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#1047 Adding Python version of snake game
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#1048 Adding python version of space invaders
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution

#1310 Adding Contribution to 136.2
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1313 add contribution to coding challenge 143
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#1314 Update 059-steering-text-paths.md
  _CodingChallenges/059-steering-text-paths.md
Labels: Community Contribution

#1320 Added my contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1322 new contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1321 Adding contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1323 Adding my community contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1324 Ray Casting w/o rotation
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1325 Update 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1326 Adding Contribution to CC145
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1328 Update 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1330 Update 144-black-hole-visualization.md
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1332 Added new contribution
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1334 added example to CC 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1336 [CC 146] Add contribution with geometrical distortions correction
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1337 Update 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1339 Update 146-rendering-ray-casting.md
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1342 Adding Contribution
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1344 adding my contribution
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1345 Adding my contribution (Challenge #145)
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1341 Adding a feature to add recommended community references
  _jekyll/includes/3-modules/link-list.html
  _jekyll/layouts/video.html
  unit_testing/formats.js
Labels: Website

#1348 Adding script to check code variations
  CodingChallenge_Variations.md
  checkVariations.js
  package-lock.json
  package.json
Labels: Repository

#1351 Trying out new Community References
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Suggested

#1343 Added label for previous/next video button
  _jekyll/layouts/video.html
  assets/css/2-base/_navigation.sass
Labels: Website, accessibility

#1354 Adding my community contribution (again)
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#1352 added community contribution
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#1360 yeah just trying to contribute my example
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1361 Update 146-rendering-ray-casting.md
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1362 Adding DHALF.txt as Community Reference for CC90
  _CodingChallenges/090-floyd-steinberg-dithering.md
Labels: Community Suggested

#1364 Added klein bottle contribution
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1315 Add P5 version of CC 132 fluid simulation
  CodingChallenges/CC_132_FluidSimulation/P5/fluid.js
  CodingChallenges/CC_132_FluidSimulation/P5/fluid_utils.js
  CodingChallenges/CC_132_FluidSimulation/P5/index.html
  CodingChallenges/CC_132_FluidSimulation/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#1333 CC145 Processing Port
  CodingChallenges/CC_145_Ray_Casting/Processing/CC_145_Ray_Casting/CC_145_Ray_Casting.pde
  CodingChallenges/CC_145_Ray_Casting/Processing/CC_145_Ray_Casting/boundary.pde
  CodingChallenges/CC_145_Ray_Casting/Processing/CC_145_Ray_Casting/particle.pde
  CodingChallenges/CC_145_Ray_Casting/Processing/CC_145_Ray_Casting/ray.pde
Labels: Code Portation (p5.js/Processing)

#1369 Update 146-rendering-ray-casting.md
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#1370 Update 092-xor.md
  _CodingChallenges/092-xor.md
Labels: Community Contribution

#1373 Rubik's Cube CC
  _CodingChallenges/142.1-rubiks-cube.md
Labels: Community Contribution

#1375 Add 404 to the website
  404.md
Labels: Website

#1376 Add contribution by @fabritsius
  _CodingChallenges/121.1-logo-interpreter.md
Labels: Community Contribution

#1377 Update 056-attraction-repulsion.md
  _CodingChallenges/056-attraction-repulsion.md
Labels: Community Contribution

#1206 Update 021-mandelbrot-p5.md
  _CodingChallenges/021-mandelbrot-p5.md
Labels: Community Contribution

#1385 Update 1.3-tabular-data-graphing.md
  _Courses/data-and-apis/1.3-tabular-data-graphing.md
Labels: Website

#1380 Rewrote the navigation section.
  _jekyll/includes/2-base/footer.html
  _jekyll/includes/2-base/head.html
  _jekyll/includes/2-base/navigation.html
  _jekyll/layouts/base.html
  assets/css/1-tools/_vars.sass
  assets/css/2-base/_navigation.sass
  assets/javascript/functions.js
Labels: Website
