Repository CodingTrain/website, pull requests merged in 2019-12, with the labels that each got.

#1964 change it editable and more slowly.
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#1972 Update 2-teachable-game.md
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1975 Update 2-teachable-game.md
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#1974 Fixing #1973
  _jekyll/includes/3-modules/video-list.html
  _jekyll/layouts/series-index.html
Labels: Website

#1979 Add first two community contributions to the Minimax challenge!
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#1980 Update 154-tic-tac-toe-minimax.md
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#1982 Update 154-tic-tac-toe-minimax.md
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#1981 C Implementation
  CodingChallenges/CC_154_Tic_Tac_Toe_Minimax/C/Main.c
Labels: Community Contribution

#1985 Community Contribution added
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#1987 Draw, Reduce, Make Curves
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#1990 Update 115-snake-game-redux.md
  _CodingChallenges/115-snake-game-redux.md
Labels: Community Contribution

#1993 Frontal cone view + Obstacle
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#1995 Reproduction and Ball Paint Mechanics + Speed
  _CodingChallenges/053-random-walk-levy.md
Labels: Community Contribution

#2000 154-tic-tac-toe: minimax that thinks about depth
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2001 added tic tac toe contribution
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2005 Update 124-flocking-boids.md
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#2006 Text Fireworks
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2008 Update 074-clock.md
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2011 Navigation Bar Drop Down Menus and Accessibility
  _jekyll/includes/2-base/navigation.html
  assets/css/2-base/_header.sass
  assets/css/2-base/_navigation.sass
  assets/javascript/functions.js
Labels: Enhancement, Website, accessibility

#2025 "Blooming" Effect and Rainbow Colors
  _CodingChallenges/014-fractaltree.md
Labels: Community Contribution

#2026 Snowflake generator with more features
  _CodingChallenges/155-kaleidoscope-snowflake.md
Labels: Community Contribution
