Repository CodingTrain/website, pull requests merged in 2019-10, with the labels that each got.

#1741 Added Contribution To CC27 - Fireworks
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#1747 Drawing with Fourier epicycles in MATLAB!
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#1751 clock contribution: no canvas, no libaries
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#1753 triple-pendulum.md
  _CodingChallenges/093-double-pendulum.md
Labels: Community Contribution

#1754 ukulele tuner contribution
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#1755 Ukulele Tuner contribution: Pitch Trail
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#1757 Update 079-number-guessing-chatbot.md
  _CodingChallenges/079-number-guessing-chatbot.md
Labels: Community Contribution

#1761 added ukelele tuner contribution, same model new design
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#1760 New Community Contributions to the Ukalele Tuner!
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#1768 Phyllotaxis Simulator in MATLAB
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#1767 Update 126-toothpicks.md
  _CodingChallenges/126-toothpicks.md
Labels: Community Contribution

#1766 Adds new contribution from lokeshlkr@gmail.com
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#1773 Update 112-3d-rendering.md
  _CodingChallenges/112-3d-rendering.md
Labels: Community Contribution

#1771 fixing my links
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#1772 Update 148-gift-wrapping.md
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#1777 Steering Behaviors Contribution: Fancy Clock
  _CodingChallenges/059-steering-text-paths.md
Labels: Community Contribution

#1778 Add Logo Interpreter contribution
  _CodingChallenges/121.1-logo-interpreter.md
Labels: Community Contribution

#1746 Add a text for showing best record distance in TSP Challenge.
  CodingChallenges/CC_035.1_TSP/P5/sketch.js
Labels: Enhancement

#1781 Add Contribution: quickdraw scenes
  _CodingChallenges/122.2-quick-draw.md
Labels: Community Contribution

#1783 contribution to clocks
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#1782 Barnsley-Fern with a rainbow gradient
  _CodingChallenges/108-barnsley-fern.md
Labels: Community Contribution

#1786 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#1787 Update 112-3d-rendering.md
  _CodingChallenges/112-3d-rendering.md
Labels: Community Contribution

#1788 Update 089-langtonsant.md
  _CodingChallenges/089-langtonsant.md
Labels: Community Contribution

#1800 Fix: invalid `letter-spacing` unit
  assets/css/1-tools/_vars.sass
Labels: Website

#1809 Contribution: Maurer Rose linked to scroll
  _CodingInTheCabana/001-maurer-rose.md
Labels: Community Contribution

#1808 Removed potential duplicate files from CC47
  CodingChallenges/CC_047_PixelSorting/P5/PixelSorting/index.html
  CodingChallenges/CC_047_PixelSorting/P5/PixelSorting/sketch.js
  CodingChallenges/CC_047_PixelSorting/P5/data/sunflower.jpg
  CodingChallenges/CC_047_PixelSorting/P5/data/sunflower400.jpg
  CodingChallenges/CC_047_PixelSorting/P5/sketch.js
Labels: Enhancement

#1815 added md file related to Guest tutorial 4
  _GuestTutorials/004-emily-xie-matrix-digital-rain.md
Labels: Community Contribution

#1814 2048 Contribution: 2048 with basic animation
  _CodingChallenges/094.1-2048.md
Labels: Community Contribution

#1817 Update 152-rdp-algorithm.md
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#1818 Added Java Maze Generator
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#1819 Update 152-rdp-algorithm.md
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#1823 added rdp contribution, "performing rdp on path for fourier drawing"
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#1826 Add project to chrome dinosaur coding challenge
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#1825 My contribution
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#1833 Add contrib to "Polar Perlin Noise Loops" - "Ranunculaceae"
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1841 collatz-conjecture: it grows now
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1844 Added contribution
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1846 Update 002-collatz-conjecture.md
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1853 10Print contribution, Random gradient
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#1852 Update 002-collatz-conjecture.md
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1854 Collatz conjecture contribution
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1856 Animation in p5.js
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1858 My Contribution Collatz Sea Tree
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1861 Collatz Conjecture Sea Weed
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1867 Added Contribution: CC 2 Collatz Conjecture | CollatzSunrise
  _CodingInTheCabana/002-collatz-conjecture.md
Labels: Community Contribution

#1865 add back to top button
  Gemfile.lock
  _jekyll/includes/3-modules/back-to-top-button.html
  _jekyll/layouts/base.html
  assets/css/4-modules/_back-to-top-button.sass
  assets/css/main.sass
  assets/javascript/functions.js
Labels: Website

#1868 Hello GitHub Actions
  .github/workflows/nodejs.yml
  .github/workflows/ruby.yml
Labels: CI, Repository, Unit Testing
