Repository CodingTrain/website, pull requests merged in 2019-02, with the labels that each got.

#1052 Update 130.1-fourier-transform-drawing.md
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#1057 Added contribution "Manipulating Fourier Transform Drawings"
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#1050 Adding python version of mitosis simulation
  _CodingChallenges/006-mitosis-p5.md
Labels: Community Contribution

#1063 Processing Version of CC131
  CodingChallenges/CC_131_BouncingDVDLogo/Processing/CC_131_BouncingDVDLogo/CC_131_BouncingDVDLogo.pde
  CodingChallenges/CC_131_BouncingDVDLogo/Processing/CC_131_BouncingDVDLogo/dvd_logo.png
Labels: Code Portation (p5.js/Processing)

#1069 Add contribution: Bouncing DVD Logo in 3D
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1068 Update 059-steering-text-paths.md
  _CodingChallenges/059-steering-text-paths.md
Labels: Community Contribution

#1070 Update to p5 version 0.7.3
  CodingChallenges/CC_109_subscriber_map/P5/index.html
Labels: Fix

#1071 Community contribution [Bouncing 90s Screensaver]
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1072 Added Contribution to #131 - VerletDVDLogo
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1085 Adding https://dvd.4ty2.fun to community contributions
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#858 Add addtional info for screen readers
  _jekyll/includes/3-modules/video-card.html
  assets/css/2-base/_global.sass
Labels: Website, accessibility

#1094 New contribution
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1103 Flow around circle
  _CodingChallenges/132-fluid-simulation.md
Labels: Community Contribution

#1105 Added my version of Double Pendulum
  _CodingChallenges/093-double-pendulum.md
Labels: Community Contribution

#1107 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1109 Add my times tables
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1111 CC_130 processing port
  CodingChallenges/CC_130_Fourier_Transform_3/Processing/CC_130_Fourier_Transform/CC_130_Fourier_Transform.pde
  CodingChallenges/CC_130_Fourier_Transform_3/Processing/CC_130_Fourier_Transform/Complex_Number.pde
  CodingChallenges/CC_130_Fourier_Transform_3/Processing/CC_130_Fourier_Transform/DFT.pde
Labels: Code Portation (p5.js/Processing)

#1112 Added my project
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1113 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1114 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1116 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1118 Added contribution
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1122 CC130 Processing Port
  CodingChallenges/CC_130_Fourier_Transform_1/Processing/CC_130_Fourier_Transform/CC_130_Fourier_Transform.pde
  CodingChallenges/CC_130_Fourier_Transform_1/Processing/CC_130_Fourier_Transform/DFT.pde
  CodingChallenges/CC_130_Fourier_Transform_1/Processing/CC_130_Fourier_Transform/train.json
  CodingChallenges/CC_130_Fourier_Transform_1/Processing/CC_130_Fourier_Transform/wave.pde
Labels: Code Portation (p5.js/Processing)

#1124 Innovative corner hit prediction
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1125 Update 031-flappybird.md
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#1133 Contribution: Changing heart
  _CodingChallenges/134-heart-curve.md
Labels: Community Contribution

#1132 Added Contribution To CC #134 | LoveHearts
  _CodingChallenges/134-heart-curve.md
Labels: Community Contribution

#1128 MotusArt contribution
  _CodingChallenges/011-perlinnoiseterrain.md
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#1131 Rainbow Heart
  _CodingChallenges/134-heart-curve.md
Labels: Community Contribution

#1138 Update 134-heart-curve.md
  _CodingChallenges/134-heart-curve.md
Labels: Community Contribution

#1144 P5 Version of CC134.2 & P5 Port of CC135
  CodingChallenges/CC_134_Heart_Curve_2/P5/index.html
  CodingChallenges/CC_134_Heart_Curve_2/P5/sketch.js
  CodingChallenges/CC_135_GIF_Loop/P5/index.html
  CodingChallenges/CC_135_GIF_Loop/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#1146 Update 131-bouncing-dvd-logo.md
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#1147 Update 103-fire-effect.md
  _CodingChallenges/103-fire-effect.md
Labels: Community Contribution

#1148 Fixed contribution link on challenge 133
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution, Fix

#1154 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1155 Update 133-times-tables-cardioid.md
  _CodingChallenges/133-times-tables-cardioid.md
Labels: Community Contribution

#1156 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#1159 Rainbow Perlin Noise loop in 3d
  _CodingChallenges/136-polar-perlin-noise-loops.md
Labels: Community Contribution

#1164 Bezier Curve Polar Noise contribution.
  _CodingChallenges/136-polar-perlin-noise-loops.md
Labels: Community Contribution

#1160 Update Node Dependencies
  package-lock.json
  package.json
  unit_testing/package-lock.json
  unit_testing/package.json
Labels: Repository

#1166 P5 Port of CC136.2
  CodingChallenges/CC_136_Polar_Noise_Loop_2/P5/index.html
  CodingChallenges/CC_136_Polar_Noise_Loop_2/P5/noiseLoop.js
  CodingChallenges/CC_136_Polar_Noise_Loop_2/P5/particle.js
  CodingChallenges/CC_136_Polar_Noise_Loop_2/P5/sketch.js
  CodingChallenges/CC_136_Polar_Noise_Loop_2/Processing/CC_136_Polar_Noise_Loop_2/CC_136_Polar_Noise_Loop_2.pde
Labels: Code Portation (p5.js/Processing)

#1167 Adding my contribution
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#1168 Update 062.1-plinko.md
  _CodingChallenges/062.1-plinko.md
Labels: Community Contribution
