Repository CodingTrain/website, pull requests merged in 2019-01, with the labels that each got.

#956 Contribution from PR#825
  _CodingChallenges/121.1-logo-interpreter.md
  _Tutorials/9-additional-topics/9.1-transformations-part-1.md
Labels: Community Contribution

#967 Contribution to CC #129 - KochStar
  _CodingChallenges/129-koch-snowflake.md
Labels: Community Contribution

#963 Transcribe Binary_To_Decimal to Processing.
  CodingChallenges/CC_119_Binary_to_Decimal_Conversion/Processing/CC_119_Binary_to_Decimal_Conversion/CC_119_Binary_to_Decimal_Conversion.pde
  CodingChallenges/CC_119_Binary_to_Decimal_Conversion/Processing/CC_119_Binary_to_Decimal_Conversion/bit.pde
Labels: Code Portation (p5.js/Processing)

#964 Transcribe Bit_Shifting to Processing.
  CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/Button.pde
  CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/CC_120_Bit_Shifting.pde
  CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/Label.pde
  CodingChallenges/CC_120_Bit_Shifting/Processing/CC_120_Bit_Shifting/bit.pde
Labels: Code Portation (p5.js/Processing)

#965 Transcribing Superellipse to Processing.
  CodingChallenges/CC_019_Superellipse/Processing/CC_019_Superellipse/CC_019_Superellipse.pde
  CodingChallenges/CC_019_Superellipse/Processing/CC_019_Superellipse/Slider.pde
Labels: Code Portation (p5.js/Processing)

#970 Add "Brownian Crystal Snowflake" by PyBlend
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#720 Update sketch_11_10_BlobTracking_lifespan.pde
  Tutorials/Processing/11_video/sketch_11_10_BlobTracking_lifespan/sketch_11_10_BlobTracking_lifespan.pde
Labels: Enhancement

#968 Transcribe Asteroids sample to Processing.
  CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Asteroid.pde
  CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/CC_046_Asteroids.pde
  CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Laser.pde
  CodingChallenges/CC_046_Asteroids/Processing/CC_046_Asteroids/Ship.pde
Labels: Code Portation (p5.js/Processing)

#712 Frogger game (CC_72) in p5.js
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/car.js
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/frog.js
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/index.html
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/log.js
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/rectangle.js
  CodingChallenges/CC_072_Frogger/CC_072_Frogger_original_p5.js/sketch.js
Labels: Code Portation (p5.js/Processing)

#961 Fix 128
  CodingChallenges/CC_128_SketchRNN_Snowflakes/P5/sketch.js
Labels: Enhancement

#971 Transcribe SmartRockets to Processing.
  CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/CC_029_SmartRockets.pde
  CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Dna.pde
  CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Population.pde
  CodingChallenges/CC_029_SmartRockets/Processing/CC_029_SmartRockets/Rocket.pde
Labels: Code Portation (p5.js/Processing)

#974 Added contribution
  _CodingChallenges/015-fractaltreearray.md
Labels: Community Contribution

#973 Transcribe DLA to Processing
  CodingChallenges/CC_034_DLA/Processing/CC_034_DLA/CC_034_DLA.pde
  CodingChallenges/CC_034_DLA/Processing/CC_034_DLA/Walker.pde
Labels: Code Portation (p5.js/Processing)

#977 Contribution To CC #117 - Glowing LED Watch
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#985 Transcribe "attraction repulsion" to Processing.
  CodingChallenges/CC_056_attraction_repulsion/Processing/CC_056_attraction_repulsion/CC_056_attraction_repulsion.pde
  CodingChallenges/CC_056_attraction_repulsion/Processing/CC_056_attraction_repulsion/Particle.pde
Labels: Code Portation (p5.js/Processing)

#984 Transcribe "Star Patterns" to Processing.
  CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/CC_054_StarPatterns.pde
  CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Edge.pde
  CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Hankin.pde
  CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Polygon.pde
  CodingChallenges/CC_054.1_StarPatterns/Processing/CC_054_StarPatterns/Slider.pde
Labels: Code Portation (p5.js/Processing)

#983 Transcribe "random walk levy" to Processing.
  CodingChallenges/CC_053_random_walk_levy/Processing/CC_053_random_walk_levy/CC_053_random_walk_levy.pde
Labels: Code Portation (p5.js/Processing)

#988 My Quick Sorting algorithm for Pixel Sorting.
  _CodingChallenges/047-pixelsorting.md
Labels: Community Contribution

#982 Transcribe "random walk" to Processing.
  CodingChallenges/CC_052_random_walk/Processing/CC_052_random_walk/CC_052_random_walk.pde
Labels: Code Portation (p5.js/Processing)

#981 Transcribe A-star to Processing.
  CodingChallenges/CC_051_astar/Processing/CC_051_astar/CC_051_astar.pde
  CodingChallenges/CC_051_astar/Processing/CC_051_astar/Spot.pde
Labels: Code Portation (p5.js/Processing)

#993 Transcribe "Inverse Kinematics Array" (part 4) to Javascript.
  CodingChallenges/CC_064.4_InverseKinematics_array/P5/index.html
  CodingChallenges/CC_064.4_InverseKinematics_array/P5/segment.js
  CodingChallenges/CC_064.4_InverseKinematics_array/P5/sketch.js
  CodingChallenges/CC_064.4_InverseKinematics_array/P5/tentacle.js
Labels: Code Portation (p5.js/Processing)

#996 Super Shape with more Controls
  _CodingChallenges/023-supershape2d.md
Labels: Community Contribution

#995 Spherical Geometry WEBGL
  _CodingChallenges/025-spheregeometry.md
Labels: Community Contribution

#994 3D SuperShape with WEBGL
  _CodingChallenges/026-supershape3d.md
Labels: Community Contribution

#999 Contribution to CC #16 : L-SystemCreator
  _CodingChallenges/016-lsystem.md
Labels: Community Contribution

#1000 Removed one of the ";"
  CodingChallenges/CC_035.4_TSP_GA/P5/ga.js
Labels: Fix

#980 Transcribe "tweets by month" to Processing.
  CodingChallenges/CC_048_TweetsByMonth/Processing/CC_048_TweetsByMonth/CC_048_TweetsByMonth.pde
  CodingChallenges/CC_048_TweetsByMonth/Processing/CC_048_TweetsByMonth/flotus.json
  CodingChallenges/CC_048_TweetsByMonth/Processing/CC_048_TweetsByMonth/potus.json
Labels: Code Portation (p5.js/Processing)

#1002 Link doesn't work on mobile devices -fix
  assets/css/2-base/_navigation.sass
Labels: Fix, Website

#1001 Transcribe "steering evolution" to Processing.
  CodingChallenges/CC_069_steering_evolution/Processing/CC_069_steering_evolution/CC_069_steering_evolution.pde
  CodingChallenges/CC_069_steering_evolution/Processing/CC_069_steering_evolution/Vehicle.pde
Labels: Code Portation (p5.js/Processing)

#998 Transcribe "binary tree viz" to Processing.
  CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/CC_065_2_binary_tree_viz.pde
  CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/Node.pde
  CodingChallenges/CC_065.2_binary_tree_viz/Processing/CC_065_2_binary_tree_viz/Tree.pde
Labels: Code Portation (p5.js/Processing)

#976 Transcribing Pixel Sorting to Javascript.
  CodingChallenges/CC_047_PixelSorting/P5/PixelSorting/data/sunflower.jpg
  CodingChallenges/CC_047_PixelSorting/P5/PixelSorting/index.html
  CodingChallenges/CC_047_PixelSorting/P5/PixelSorting/sketch.js
  CodingChallenges/CC_047_PixelSorting/P5/data/sunflower100.jpg
  CodingChallenges/CC_047_PixelSorting/P5/index.html
  CodingChallenges/CC_047_PixelSorting/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#997 Transcribe "binary tree" to Processing.
  CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/CC_065_1_binary_tree.pde
  CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/Node.pde
  CodingChallenges/CC_065.1_binary_tree/Processing/CC_065_1_binary_tree/Tree.pde
Labels: Code Portation (p5.js/Processing)

#991 Transcribe "Inverse Kinematics - Fixed" to Javascript.
  CodingChallenges/CC_064.3_InverseKinematics_fixed/P5/index.html
  CodingChallenges/CC_064.3_InverseKinematics_fixed/P5/robotarm.js
  CodingChallenges/CC_064.3_InverseKinematics_fixed/P5/segment.js
  CodingChallenges/CC_064.3_InverseKinematics_fixed/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#990 Transcribe "butterfly wings" to processing.
  CodingChallenges/CC_060_Butterfly_Wings/Processing/CC_060_Butterfly_Wings/CC_060_Butterfly_Wings.pde
Labels: Code Portation (p5.js/Processing)

#1005 Update 111-animated-sprite.md
  _CodingChallenges/111-animated-sprite.md
Labels: Community Contribution

#1007 Update 024-perlinnoiseflowfield.md
  _CodingChallenges/024-perlinnoiseflowfield.md
Labels: Community Contribution

#735 Added hover effect on .video-card
  assets/css/4-modules/_video-card.sass
Labels: Website

#1011 Update 124-flocking-boids.md
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#1019 Rainbow Epicycles: Unicorn train driver
  _CodingChallenges/130-fourier-transform-drawing.md
Labels: Community Contribution

#1020 Change "epicyles" by orbits and added link
  _CodingChallenges/130-fourier-transform-drawing.md
Labels: Community Contribution

#1006 Transcribe "snakes and ladders" to Processing.
  CodingChallenges/CC_091_snakesladders/P5/sketch.js
  CodingChallenges/CC_091_snakesladders/P5/tile.js
  CodingChallenges/CC_091_snakesladders/Processing/CC_091_snakesladders/CC_091_snakesladders.pde
  CodingChallenges/CC_091_snakesladders/Processing/CC_091_snakesladders/Label.pde
  CodingChallenges/CC_091_snakesladders/Processing/CC_091_snakesladders/Player.pde
  CodingChallenges/CC_091_snakesladders/Processing/CC_091_snakesladders/Tile.pde
Labels: Code Portation (p5.js/Processing)

#1021 Update URLs
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#1022 Update URLs #2
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#1024 Update URLs again
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#1031 Add community contributions to CC_105_tf_polynomial_regression
  _CodingChallenges/105-polynomial-regression-tfjs.md
Labels: Community Contribution

#1035 Update 053-random-walk-levy.md
  _CodingChallenges/053-random-walk-levy.md
Labels: Community Contribution
