Repository CodingTrain/website, pull requests merged in 2020-12, with the labels that each got.

#2910 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2911 Adding Timestamps and Fixing Relative Links in YouTube Descriptions
  _scripts/generate-youtube-descriptions.js
Labels: YouTube, bug

#2909 Adding page for Discord .env Video
  _learning/bots/discord/04-dotenv.md
  learning/bots/discord/04-dotenv/Node/.env-sample
  learning/bots/discord/04-dotenv/Node/bot.js
  learning/bots/discord/04-dotenv/Node/package-lock.json
  learning/bots/discord/04-dotenv/Node/package.json
Labels: New Pages

#2914 Update 145-2d-ray-casting.md
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#2918 formatting fix cc138
  _CodingChallenges/138-angry-birds.md
Labels: bug

#2920 adding missing html in ml5 8.4
  learning/ml5/8.4-cnn-image-classification/mask/index.html
Labels: bug

#2919 Adding page for ml5 DoodleNet Video
  _learning/ml5/9.1-doodlenet.md
  learning/ml5/9.1-doodlenet/mouse/index.html
  learning/ml5/9.1-doodlenet/mouse/sketch.js
  learning/ml5/9.1-doodlenet/template/index.html
  learning/ml5/9.1-doodlenet/template/sketch.js
  learning/ml5/9.1-doodlenet/video/index.html
  learning/ml5/9.1-doodlenet/video/sketch.js
Labels: New Pages

#2936 Adding contributions for @abhay2008
  _CodingChallenges/005-space-invaders-p5.md
  _CodingChallenges/032.1-agar.md
Labels: Community Contribution

#2937 Random Walker Contribution: Adding Perlin Nosie
  _CodingChallenges/052-random-walk.md
Labels: Community Contribution

#2942 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2943 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2947 Update 016-lsystem.md
  _CodingChallenges/016-lsystem.md
Labels: Community Contribution

#2940 Trex game with automatic jumping
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2948 Outdated Snake by OutdatedGuy
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2949 Raycasting contribution(Processing): Ease control and togglable mouse…
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#2951 Adding page for discord 5 - posting gifs
  _learning/bots/discord/05-posting-gifs.md
  learning/bots/discord/05-posting-gifs/Node/.env-sample
  learning/bots/discord/05-posting-gifs/Node/bot.js
  learning/bots/discord/05-posting-gifs/Node/package-lock.json
  learning/bots/discord/05-posting-gifs/Node/package.json
Labels: New Pages

#2956 Update 147-chrome-dinosaur.md
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2961 Update 138-angry-birds.md
  _CodingChallenges/138-angry-birds.md
Labels: Community Contribution

#2962 Update 063.1-unikitty-flag.md
  _CodingChallenges/063.1-unikitty-flag.md
Labels: Community Contribution

#2963 Update 100.1-neuroevolution-flappy-bird.md
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#2964 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2965 Add my contribution to the bottom
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2967 Update 147-chrome-dinosaur.md
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2971 We have done the breakout game in p5.js
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2970 Update 062.1-plinko.md
  _CodingChallenges/062.1-plinko.md
Labels: Community Contribution

#2972 Update 005-space-invaders-p5.md
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution
