Repository CodingTrain/website, pull requests merged in 2020-11, with the labels that each got.

#2842 Update 001-maurer-rose.md
  _challenges/coding-in-the-cabana/001-maurer-rose.md
Labels: Community Contribution

#2838 Update 157-zoom-annotations.md
  _CodingChallenges/157-zoom-annotations.md
Labels: Community Contribution

#2843 Update 1.1-fetch.md
  _Courses/data-and-apis/1.1-fetch.md
Labels: Community Contribution

#2844 Removing Hacktoberfest Information
  .github/pull_request_template.md
  README.md
Labels: Hacktoberfest, Repository

#2845 A* Contribution: Lightning Visualisation
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2849 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2848 Update 1.2-tabular-data.md
  _Courses/data-and-apis/1.2-tabular-data.md
Labels: Community Contribution

#2846 Added md files programming-with-text video 9.1-9.3
  _learning/programming-with-text/9.1-what-is-firebase-database-as-a-service.md
  _learning/programming-with-text/9.2-firebase-saving-data.md
  _learning/programming-with-text/9.3-firebase-retrieving-data.md
Labels: New Pages

#2853 Update 154-tic-tac-toe-minimax.md
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2854 Phyllotaxis contribution: animating growth angle
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#2850 Add github link to core contribution guide
  _Guides/core-contribution-guide.md
  docker-compose.yml
Labels: Documentation

#2855 StarPatterns contribution: Integrated p5.sound <3
  _CodingChallenges/054.1-starpatterns.md
Labels: Community Contribution

#2860 Fixing Contributions on cc157
  _CodingChallenges/157-zoom-annotations.md
Labels: bug

#2861 Adding Pages for Discord Bot Videos 1 and 2
  _jekyll/includes/2-base/navigation.html
  _learning/bots/discord/01-introduction.md
  _learning/bots/discord/02-dev-portal.md
  _learning/bots/discord/index.md
Labels: New Pages

#2851 I added my flappy bird thingbob
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2859 3D terrain contribution: 3D mirror-ish
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#2862 Update 117-seven-segment.md
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#2864 Toothpicks Contribution - Ulam Warburton Version
  _CodingChallenges/126-toothpicks.md
Labels: Community Contribution

#2865 Submitting an contribution
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2866 Adding Page for Discord Bot Video 3
  _learning/bots/discord/03-discordjs.md
  learning/bots/discord/03-discordjs/Nodejs/bot.js
  learning/bots/discord/03-discordjs/Nodejs/package-lock.json
  learning/bots/discord/03-discordjs/Nodejs/package.json
Labels: New Pages

#2872 Raycasting contribution: 2D Ray-casting with p5py
  _CodingChallenges/145-2d-ray-casting.md
Labels: Community Contribution

#2869 created rock paper scissors utilizing vue.js, ml5.js and p5.js
  _CodingChallenges/157-zoom-annotations.md
Labels: Community Contribution

#2874 Renaming Discord Bot 3 Code Folder
  learning/bots/discord/03-discordjs/Node/bot.js
  learning/bots/discord/03-discordjs/Node/package-lock.json
  learning/bots/discord/03-discordjs/Node/package.json
Labels: bug

#2877 raycasting 3d contribution: Doom made out of checkboxes
  _CodingChallenges/146-rendering-ray-casting.md
Labels: Community Contribution

#2878 game of life contribution: step by step running
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2881 angry birds rebuilt
  angry birds
Labels: Community Contribution

#2882 Update 001-maurer-rose.md
  _challenges/coding-in-the-cabana/001-maurer-rose.md
Labels: Community Contribution

#2883 Bounce.md
  _beginners/p5js/6.1-opp-intro.md
Labels: Community Contribution

#2888 fractal tree with mouse dynamics
  _CodingChallenges/014-fractaltree.md
Labels: Community Contribution

#2889 Update 6.1-opp-intro.md link: https://editor.p5js.org/arnavraspberrypi/sketches/G9YjgIuOQ
  _beginners/p5js/6.1-opp-intro.md
Labels: Community Contribution

#2895 Added a browser based artwork contribution
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2892 Adding page for cnn image classification video
  _learning/ml5/8.4-cnn-image-classification.md
  learning/ml5/8.4-cnn-image-classification/P5/index.html
  learning/ml5/8.4-cnn-image-classification/P5/sketch.js
  learning/ml5/8.4-cnn-image-classification/mask/index.html
  learning/ml5/8.4-cnn-image-classification/mask/sketch.js
Labels: New Pages

#2897 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2898 Update 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2901 My first ever Contribution !!!
  _CodingChallenges/083-doodle-chrome-extension.md
Labels: Community Contribution

#2902 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2903 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution
