Repository CodingTrain/website, pull requests merged in 2020-03, with the labels that each got.

#2149 Add port to p5.js of Coding Challenge 102: 2D Water Ripple
  CodingChallenges/CC_102_WaterRipples/P5/index.html
  CodingChallenges/CC_102_WaterRipples/P5/sketch.js
  _CodingChallenges/102-2d-water-ripple.md
Labels: Code Portation (p5.js/Processing)

#2150 Visualizing a Binary Tree Contrib: equally spaced nodes
  _CodingChallenges/065.1-binary-tree.md
Labels: Community Contribution

#2153 Polynomial regression contribution
  _CodingChallenges/105-polynomial-regression-tfjs.md
Labels: Community Contribution

#2152 KNN Class. contribution: teachable machine clone
  _learning/ml5/5.1-knn-classification-1.md
Labels: Community Contribution

#2131 Starting Nature of Code Pages
  _jekyll/includes/2-base/navigation.html
  _learning/index.md
  _learning/nature-of-code/0.0-welcome.md
  _learning/nature-of-code/0.1-introduction.md
  _learning/nature-of-code/1.1-what-is-a-vector.md
  _learning/nature-of-code/index.md
  learning/nature-of-code/1.1_what_is_a_vector/P5/index.html
  learning/nature-of-code/1.1_what_is_a_vector/P5/sketch.js
  learning/nature-of-code/1.1_what_is_a_vector/P5/walker.js
  learning/nature-of-code/1.2_vector_math/P5/index.html
  learning/nature-of-code/1.2_vector_math/P5/sketch.js
  learning/nature-of-code/1.2_vector_math/P5/walker.js
  learning/nature-of-code/1.3_random_vector/p5-multi/random_vector/index.html
  learning/nature-of-code/1.3_random_vector/p5-multi/random_vector/sketch.js
  learning/nature-of-code/1.3_random_vector/p5-multi/walker/index.html
  learning/nature-of-code/1.3_random_vector/p5-multi/walker/sketch.js
  learning/nature-of-code/1.3_random_vector/p5-multi/walker/walker.js
  unit_testing/files.js
  unit_testing/yaml.test.js
Labels: New Pages

#2155 Update 134.1-heart-curve.md
  _CodingChallenges/134.1-heart-curve.md
Labels: Community Contribution

#2158 075-clock.md
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2157 Adding page for NOC 1.2
  _learning/nature-of-code/1.2-vector-math.md
  learning/nature-of-code/1.2_vector_math/P5/sketch.js
  learning/nature-of-code/1.2_vector_math/P5/walker.js
Labels: New Pages

#2162 Challenge #148: Gift Wrapping Algorithm
  _CodingChallenges/148-gift-wrapping.md
Labels: Community Contribution

#2168 Added Bogoesque algorithm adaptation
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2169 Pi Day Digits Search page
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/index.js
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/package-lock.json
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/package.json
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/pi-million.txt
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/public/index.html
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/public/sketch.js
  CodingChallenges/CC_156_Pi_Digits/p5-multi/node/public/style.css
  CodingChallenges/CC_156_Pi_Digits/p5-multi/p5/index.html
  CodingChallenges/CC_156_Pi_Digits/p5-multi/p5/pi-million.txt
  CodingChallenges/CC_156_Pi_Digits/p5-multi/p5/sketch.js
  CodingChallenges/CC_156_Pi_Digits/p5-multi/p5/style.css
  _CodingChallenges/156-pi-digits.md
Labels: New Pages

#2171 Community Contribution for Peeking in π
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2170 Reaction-Diffusion Contribution: Cuda support for faster computation
  _CodingChallenges/013-reactiondiffusion-p5.md
Labels: Community Contribution

#2163 added CC_025 p5.js version (spherical geometry)
  CodingChallenges/CC_025_SphereGeometry/P5/index.html
  CodingChallenges/CC_025_SphereGeometry/P5/sketch.js
  CodingChallenges/CC_025_SphereGeometry/Processing/CC_025_SphereGeometry/CC_025_SphereGeometry.pde
  _CodingChallenges/025-spheregeometry.md
Labels: Code Portation (p5.js/Processing)

#2159 Adding Page for NOC 1.3
  _learning/nature-of-code/1.3-random-vector.md
  learning/nature-of-code/1.3_random_vector/p5-multi/random_vector/sketch.js
  learning/nature-of-code/1.3_random_vector/p5-multi/walker/sketch.js
  learning/nature-of-code/1.3_random_vector/p5-multi/walker/walker.js
Labels: New Pages

#2175 Adding Page for NOC 1.4
  _learning/nature-of-code/1.4-static-functions.md
Labels: New Pages

#2177 swapped links, new gif
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2180 Update 098.1-quadtree.md
  _CodingChallenges/098.1-quadtree.md
Labels: Community Contribution

#2176 Adding Page for NOC 1.5
  _learning/nature-of-code/1.5-unit-vector.md
  learning/nature-of-code/1.5_unit_vector/P5/index.html
  learning/nature-of-code/1.5_unit_vector/P5/sketch.js
Labels: New Pages

#2182 Adding page for NOC 1.6
  _learning/nature-of-code/1.6-acceleration-vector.md
  learning/nature-of-code/1.6_acceleration_vector/P5/index.html
  learning/nature-of-code/1.6_acceleration_vector/P5/mover.js
  learning/nature-of-code/1.6_acceleration_vector/P5/sketch.js
Labels: New Pages

#2183 Community Contribution to Noise Terrain 011
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#2186 Chrome Dinosaur Game contribution
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2187 Adding page for NOC 2.1
  _learning/nature-of-code/2.1-simulating-forces.md
  learning/nature-of-code/2.1_simulating_forces/P5/index.html
  learning/nature-of-code/2.1_simulating_forces/P5/mover.js
  learning/nature-of-code/2.1_simulating_forces/P5/sketch.js
Labels: New Pages

#2189 Bit Shifting Contribution: BitViz
  _CodingChallenges/120-bit-shifting.md
Labels: Community Contribution

#2191 just implemented in java
  _CodingChallenges/098.1-quadtree.md
Labels: Community Contribution

#2196 Page for NOC 2.2
  _learning/nature-of-code/2.2-mass-acceleration.md
  learning/nature-of-code/2.2_mass_acceleration/P5/index.html
  learning/nature-of-code/2.2_mass_acceleration/P5/mover.js
  learning/nature-of-code/2.2_mass_acceleration/P5/sketch.js
Labels: New Pages
