Repository CodingTrain/website, pull requests merged in 2020-10, with the labels that each got.

#2616 Adding Hacktoberfest Section on README
  README.md
Labels: Hacktoberfest

#2634 added hacktoberfest description to PR template
  .github/pull_request_template.md
Labels: Hacktoberfest

#2632 Add BFS Visualizer Community Contribution
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2633 Added contribution: Midnight Colorful Rain
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#2635 Add Snake Game With Obstacles
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2636 10PRINT Rain and Snow
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2641 Perlin Noise Loop contribution: Perlin Meta Rings
  _CodingChallenges/136.1-polar-perlin-noise-loops.md
Labels: Community Contribution

#2642 10 Print contribution : 10PRINT with perlin and style
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2643 Peeking in π with number pad
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2631 Deployment previews on pull requests
  .github/workflows/featurepeek.yml
  peek.yml
Labels: CI

#2645 Add Peeking Inside Pi contribution
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2646 Add Beginners Introdunction contribution #2615
  _beginners/p5js/1.1-introduction.md
Labels: Community Contribution

#2648 Sorting Algorithms as a Color Spectrum
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2649 Updated worley noises with a ripple effect
  _challenges/coding-in-the-cabana/004-worley-noise.md
Labels: Community Contribution

#2651 Bubble Sort contribution: Sorting a picture
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#2652 Blobbly contribution: Meta Matter
  _CodingChallenges/036-blobby.md
Labels: Community Contribution

#2653 Perlin Noise Flow Field contribution : Perlin Roots
  _CodingChallenges/024-perlinnoiseflowfield.md
Labels: Community Contribution

#2654 Added my version of flappy bird (Slide the Rain).
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2656 Added new community contribution
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#2658 Update 111-animated-sprite.md
  _CodingChallenges/111-animated-sprite.md
Labels: Community Contribution

#2659 Guess Game Contribution - Implemented using react
  _CodingChallenges/079-number-guessing-chatbot.md
Labels: Community Contribution

#2660 10PRINT Contribution: 10PRINT with C# and Unity
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2661 bouncing ball contribution: changing colors and mouse interaction
  _beginners/p5js/3.1-conditional-statements.md
Labels: Community Contribution

#2662 start pattern contribution: alternative version
  _CodingChallenges/054.1-starpatterns.md
Labels: Community Contribution

#2664 Add a contribution
  _CodingChallenges/144-black-hole-visualization.md
Labels: Community Contribution

#2665 Random Colourfull Maze
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2666 Add a web app version of the original
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2668 added my own version of "flappy bird"
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2667 created web editor version of RiveScript chatbot
  _CodingChallenges/079-number-guessing-chatbot.md
Labels: Missing code

#2669 Evolutionary Steering Behaviour with Boids, Predators, Microbes and Hiding Places
  _CodingChallenges/069.1-steering-evolution.md
Labels: Community Contribution

#2671 Update 027-fireworks.md
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2672 Dancing cube with mouse interaction
  _CodingChallenges/086-beesandbombs.md
Labels: Community Contribution

#2673 Created a p5 Port using OOP
  _CodingChallenges/007-solarsystemgenerator.md
Labels: Community Contribution

#2675 Terrain Generation Contribution: Synthwave
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#2678 Added mouse interaction with sin and cos waves
  _CodingChallenges/014-fractaltree.md
Labels: Community Contribution

#2679 can change color with speed!
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2680 color chainging star field
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2681 Clock Contribution: Fibonacci Clock
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2683 Add 3D Lissajous Pattern Generator contribution
  _CodingChallenges/116-lissajous.md
Labels: Community Contribution

#2684 Update 7.7-object-communication-2.md
  _beginners/p5js/7.7-object-communication-2.md
Labels: Community Contribution

#2691 Contribution: Double Pendulum with Matter.js
  _CodingChallenges/093-double-pendulum.md
Labels: Community Contribution

#2692 Inverse Kinematics Contribution: Robot Arm in 3D
  _CodingChallenges/064.1-forward-kinematics.md
Labels: Community Contribution

#2696 Adding Pages Contribution Guide
  _Guides/pages-contribution-guide.md
Labels: Documentation, New Pages

#2695 Update 051.1-astar.md
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2657 Translated to Japanese.
  README.ja.md
Labels: Documentation

#2699 Sorting Visualizer as a color Spectrum
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#2701 Update 114-bubble-sort.md for hacktoberfest issue #2615
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#2702 Update 035.1-tsp.md
  _CodingChallenges/035.1-tsp.md
Labels: Community Contribution

#2715 Fixing cnn code examples
  _learning/ml5/8.2-cnn-1.md
  _learning/ml5/8.3-cnn-2.md
Labels: bug

#2703 Billeh Contabution
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2704 Space Invaders contribution : Hanzi Space Invaders
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution

#2705 Snake Game contribution : Hanzi Snake Game
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2707 Adding Colourful Tic Tac Toe
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2709 Snowfall animation with static picture in background
  _CodingChallenges/088-snowfall.md
Labels: Community Contribution

#2710 Adding a contribution to the game of life coding challenge
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2711 Update 032.1-agar.md
  _CodingChallenges/032.1-agar.md
Labels: Community Contribution

#2712 pixel to centimeter
  _beginners/p5js/2.1-mousex-mousey.md
Labels: Community Contribution

#2714 Update 155-kaleidoscope-snowflake.md
  _CodingChallenges/155-kaleidoscope-snowflake.md
Labels: Community Contribution

#2717 Maze Generator: 2 Player Maze Game
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2720 Minesweeper contribution: 3D Minesweeper
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#2724 Coding challenge 88 Contribution
  _CodingChallenges/088-snowfall.md
Labels: Community Contribution

#2728 Peeking Inside Pi Coding Challenge : 2Pi a.k.a Tau
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2730 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2739 Update 156-pi-digits.md
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2733 Add community contribution to 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2734 Update 149-tic-tac-toe.md
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2743 10PRINT contribution: rain simulation
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2746 Hypnotic Phyllotaxis
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#2750 Tic Tac Toe contribution: 2 players
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2751 Update 069.1-steering-evolution.md
  _CodingChallenges/069.1-steering-evolution.md
Labels: Community Contribution

#2756 Switching to Main
  .github/workflows/gist.yml
Labels: Repository

#2758 BookofPI Contributiion - Book of PI in Morse Code
  _CodingChallenges/097.1-book-of-pi.md
Labels: Community Contribution

#2759 Algorithm Visualizer Contribution - 3D PathFinder
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2765 Added a video description of "Programming with Text"
  _learning/programming-with-text/1.3-text-input.md
Labels: New Pages

#2767 Added a video description of "Programming with Text"
  _learning/programming-with-text/1.4-loading-text-file.md
Labels: New Pages

#2769 Added a video description(10.1)
  _learning/programming-with-text/10.1-introducation.md
Labels: New Pages

#2770 add eg
  _Courses/data-and-apis/3.5-deployment.md
Labels: Community Contribution

#2772 Contribution: Evolving Flappy Bird
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#2773 Add Missing Pages in Programing with Text Series - vid 3.1
  _learning/programming-with-text/3.1-the-ritajs-library.md
Labels: New Pages

#2775 Adding Script to Generate YouTube Descriptions
  .gitignore
  _beginners/git-and-github/index.md
  _beginners/p5js/index.md
  _scripts/generate-youtube-descriptions.js
  package.json
  unit_testing/formats.js
Labels: Repository, Unit Testing

#2774 Add Missing Pages in Programing with Text Series - vids 3.2 and 3.3
  _learning/programming-with-text/3.2-the-nlp-compromise-library.md
  _learning/programming-with-text/3.3-homework-assignments-week-3.md
Labels: New Pages

#2778 Asteroids Contribution: NEAT AI and Ray Casting
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#2779 Add Missing Pages in Programing with Text Series - Series 7
  _learning/programming-with-text/10.1-introduction.md
  _learning/programming-with-text/7.1-introduction.md
  _learning/programming-with-text/7.2-context-free-grammar-with-tracery.md
  _learning/programming-with-text/7.3-context-free-grammar-with-ritajs.md
  _learning/programming-with-text/7.4-homework-assignment-session-7.md
Labels: New Pages

#2780 Update 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2782 Update 051.1-astar.md
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2785 Update 010.1-maze-dfs-p5.md
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2787 Add Missing Pages in Programing with Text Series - Session 6
  _learning/programming-with-text/6.1-introduction.md
  _learning/programming-with-text/6.2-homework-assignment-session-6.md
Labels: New Pages

#2788 Added a pygame version quicksort visualization
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2790 Added Minesweeper with Processing.py
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#2791 Add Missing Pages in Programing with Text Series - vid 5.2
  _learning/programming-with-text/5.2-assosiative-arrays.md
Labels: New Pages

#2793 Add Missing Pages in Programing with Text Series - video 1.5
  _learning/programming-with-text/1.5-javascript-string-object.md
Labels: New Pages

#2794 Community contribution on A-Star coding challenge
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2795 Add Missing Pages in Programing with Text Series - Series 8
  _learning/programming-with-text/8.1-introduction.md
  _learning/programming-with-text/8.2-http-server-with-express.md
  _learning/programming-with-text/8.3-restful-routes.md
  _learning/programming-with-text/8.4-restful-routes-with-parameters.md
  _learning/programming-with-text/8.5-saving-data-to-json-file-with-nodejs.md
  _learning/programming-with-text/8.6-api-front-end-client.md
  _learning/programming-with-text/8.7-build-your-own-api-conclusion-with-http-post.md
Labels: New Pages

#2796 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2799 Update 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2800 Adding my own modest contribution
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2626 Updated sketch.js
  learning/ml5/1.2_webcam_classification/P5/sketch.js
Labels: bug

#2801 Add Missing Pages in Programing with Text Series - video 1.6
  _learning/programming-with-text/1.6-homework-assignments-week-1.md
Labels: New Pages

#2803 Add Missing Pages in Programing with Text Series - video 5.3
  _learning/programming-with-text/5.3-homework-assignment-week-5.md
Labels: New Pages

#2804 Hacktoberfest Logo Drawing YouTube Live
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#2807 Seven-segment contribution: editable appearance
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#2808 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2809 Broken links: programming_with_text_session11
  Courses/programming_with_text/session11/README.md
Labels: bug

#2812 Quadtree and SIR Model Visualisation
  _CodingChallenges/098.1-quadtree.md
Labels: Community Contribution

#2813 TicTacToe MiniMax contribution
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2811 Adding Page for Coding Challenge
  CodingChallenges/CC_157_Zoom_Annotations/1-basic/index.html
  CodingChallenges/CC_157_Zoom_Annotations/1-basic/question.png
  CodingChallenges/CC_157_Zoom_Annotations/1-basic/sketch.js
  CodingChallenges/CC_157_Zoom_Annotations/2-final/index.html
  CodingChallenges/CC_157_Zoom_Annotations/2-final/laugh.png
  CodingChallenges/CC_157_Zoom_Annotations/2-final/love.mp4
  CodingChallenges/CC_157_Zoom_Annotations/2-final/no.png
  CodingChallenges/CC_157_Zoom_Annotations/2-final/question.png
  CodingChallenges/CC_157_Zoom_Annotations/2-final/sketch.js
  CodingChallenges/CC_157_Zoom_Annotations/2-final/yes.png
  _CodingChallenges/157-zoom-annotations.md
Labels: New Pages

#2818 added missing page in Programing with Text Series - video 5.1
  _learning/programming-with-text/5.1-introduction.md
Labels: New Pages

#2821 Display the # of COVID cases on a 3D map
  _CodingChallenges/058-earthquakeviz3d.md
Labels: Community Contribution

#2347 p5.js Unikitty Flag
  _CodingChallenges/063.1-unikitty-flag.md
Labels: Community Contribution

#2826 fix programming with text 5.3
  _learning/programming-with-text/5.3-homework-assignment-week-5.md
Labels: bug

#2827 Adding Discord Redirect Page
  _config.yml
  _jekyll/layouts/external-redirect.html
  _redirects/discord.md
Labels: Website

#2823 Added Kaleidoscope Simulation with Processing
  _CodingChallenges/155-kaleidoscope-snowflake.md
Labels: Community Contribution

#2824 Community Contribution Poisson disc sampling
  _CodingChallenges/033-poisson-disc.md
Labels: Community Contribution

#2825 Update 001-starfield.md
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2836 Map visualization contribution: Input Bay Wheels 2020 data
  _CodingChallenges/109-subscribers-map.md
Labels: Community Contribution

#2835 change the image protocol of the contribution guide
  _Guides/community-contribution-guide.md
Labels: Community Contribution

#2834 Community Contribution: Simulating An Epidemic
  _CodingChallenges/098.1-quadtree.md
Labels: Community Contribution

#2828 Fixed broken links in Courses folder (bug)
  Courses/programming_with_text/session01/README.md
  Courses/programming_with_text/session02/README.md
  Courses/programming_with_text/session03/README.md
  Courses/programming_with_text/session05/README.md
  Courses/programming_with_text/session06/README.md
  Courses/programming_with_text/session07/README.md
  Courses/programming_with_text/session08/README.md
  Courses/programming_with_text/session09/README.md
  Courses/programming_with_text/session10/README.md
Labels: Hacktoberfest, Repository

#2830 Visualizing contribution: post covid flight map
  _CodingChallenges/109-subscribers-map.md
Labels: Community Contribution

#2837 Contribution in Perlin noise terrain
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#2839 Contribution to Gif Loop: MIDI control
  _CodingChallenges/135-gif-loop.md
Labels: Community Contribution

#2840 2048 clone with same ui and colours as original
  _CodingChallenges/094.1-2048.md
Labels: Community Contribution
