Repository CodingTrain/website, pull requests merged in 2020-07, with the labels that each got.

#2403 Update 140-leibniz-formula-pi.md
  _CodingChallenges/140-leibniz-formula-pi.md
Labels: Community Contribution

#2406 Adding version of Mathematical rose patterns
  _CodingChallenges/055-roses.md
Labels: Community Contribution

#2410 Added my project to the list with links
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2417 Update 016-lsystem.md
  _CodingChallenges/016-lsystem.md
Labels: Community Contribution

#2419 Data for SEO for easier sharing and being searched
  Gemfile
  Gemfile.lock
  _config.yml
  _jekyll/includes/2-base/head.html
Labels: Enhancement, Website

#2422 Update 022-juliaset.md
  _CodingChallenges/022-juliaset.md
Labels: Community Contribution

#2424 Moving cabana videos to new site structure
  _challenges/coding-in-the-cabana/001-maurer-rose.md
  _challenges/coding-in-the-cabana/002-collatz-conjecture.md
  _challenges/coding-in-the-cabana/003-hilbert-curve.md
  _challenges/coding-in-the-cabana/004-worley-noise.md
  _challenges/coding-in-the-cabana/index.md
  _challenges/index.md
  _config.yml
  _jekyll/includes/2-base/navigation.html
  challenges/coding-in-the-cabana/001_maurer_rose/P5/index.html
  challenges/coding-in-the-cabana/001_maurer_rose/P5/sketch.js
  challenges/coding-in-the-cabana/001_maurer_rose/Processing/Cabana_001_Maurer_Rose.pde
  challenges/coding-in-the-cabana/002_collatz_conjecture/P5/index.html
  challenges/coding-in-the-cabana/002_collatz_conjecture/P5/sketch.js
  challenges/coding-in-the-cabana/002_collatz_conjecture/Processing/CollatzConjecture.pde
  challenges/coding-in-the-cabana/003_hilbert_curve/P5/index.html
  challenges/coding-in-the-cabana/003_hilbert_curve/P5/sketch.js
  challenges/coding-in-the-cabana/003_hilbert_curve/Processing/Hilbert/Hilbert.pde
  challenges/coding-in-the-cabana/004_worley_noise/P5/index.html
  challenges/coding-in-the-cabana/004_worley_noise/P5/sketch.js
  challenges/coding-in-the-cabana/004_worley_noise/Processing/worley_noise_cabana/worley_noise_cabana.pde
  landing-page.html
  package.json
  unit_testing/files.js
  unit_testing/yaml.test.js
Labels: Website

#2429 Adding Page for Marching Squares
  .eslintignore
  _challenges/coding-in-the-cabana/005-marching-squares.md
  challenges/coding-in-the-cabana/005_marching_squares/P5/OpenSimplexNoise.js
  challenges/coding-in-the-cabana/005_marching_squares/P5/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_cave/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_cave/onoise.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_cave/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_cave/squares.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_color/OpenSimplexNoise.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_color/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_color/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_image/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_image/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs/Bubble.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs_interpolation/Bubble.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs_interpolation/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_metaballs_interpolation/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_simplex_interpolation/OpenSimplexNoise.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_simplex_interpolation/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_simplex_interpolation/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_webcam/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_webcam/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/P5_worley/index.html
  challenges/coding-in-the-cabana/005_marching_squares/P5_worley/sketch.js
  challenges/coding-in-the-cabana/005_marching_squares/Processing/sketch_marching_squares/OpenSimplexNoise.java
  challenges/coding-in-the-cabana/005_marching_squares/Processing/sketch_marching_squares/sketch_marching_squares.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_color/sketch_marching_squares_color/OpenSimplexNoise.java
  challenges/coding-in-the-cabana/005_marching_squares/Processing_color/sketch_marching_squares_color/sketch_marching_squares_color.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_image/sketch_marching_squares_image/data/image0.jpg
  challenges/coding-in-the-cabana/005_marching_squares/Processing_image/sketch_marching_squares_image/sketch_marching_squares_image.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_metaballs/sketch_metaballs/Bubble.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_metaballs/sketch_metaballs/sketch_metaballs.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_metaballs_interpolation/sketch_marching_squares_metaballs_interpolation/Bubble.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_metaballs_interpolation/sketch_marching_squares_metaballs_interpolation/sketch_marching_squares_metaballs_interpolation.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_simplex_interpolation/sketch_marching_squares_simplex_noise_interpolation/OpenSimplexNoise.java
  challenges/coding-in-the-cabana/005_marching_squares/Processing_simplex_interpolation/sketch_marching_squares_simplex_noise_interpolation/sketch_marching_squares_simplex_noise_interpolation.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_webcam/sketch_marching_squares_webcam/sketch_marching_squares_webcam.pde
  challenges/coding-in-the-cabana/005_marching_squares/Processing_worley/sketch_marching_squares_worley/sketch_marching_squares_worley.pde
Labels: New Pages

#2431 Update 005-marching-squares.md
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2432 Update 005-marching-squares.md
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2435 community contribution, Marching Squares
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2437 Contribution: Marching Squares square contours
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2438 A simple spinning Phyllotaxis in vanilla JavaScript
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#2441 Maurer Rose in JavaScript
  _challenges/coding-in-the-cabana/001-maurer-rose.md
Labels: Community Contribution

#2445 Added my inspired project
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2448 Update 154-tic-tac-toe-minimax.md
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2446 Update 005-marching-squares.md
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2449 Update 012-shirley-wu-introduction-to-d3js.md
  _GuestTutorials/012-shirley-wu-introduction-to-d3js.md
Labels: Community Contribution

#2450 Add Contribution
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2451 Update 004-purplerain.md
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#2452 Marching Squares contribution: C++ 3D Marching Cubes
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2453 Update 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution

#2454 Update 005-marching-squares.md
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2461 Update 051.1-astar.md
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2459 A new Lorenz attractor with butterflies
  _CodingChallenges/012-lorenzattractor.md
Labels: Community Contribution

#2458 Update 2.3-friction.md
  _learning/nature-of-code/2.3-friction.md
Labels: Community Contribution

#2460 Update 005-marching-squares.md
  _challenges/coding-in-the-cabana/005-marching-squares.md
Labels: Community Contribution

#2464 Update 061-fractal-spirograph.md
  _CodingChallenges/061-fractal-spirograph.md
Labels: Community Contribution
