Repository CodingTrain/website, pull requests merged in 2020-02, with the labels that each got.

#2081 Tic Tac Toe MiniMax with Angular and Charts
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#2082 Added slow sort contribution
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2083 A pitch detection Game
  _CodingChallenges/151-ukulele-tuner.md
Labels: Community Contribution

#2084 Add one more reference
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2091 Added my community contribution
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2092 Astar pathfinding: using flutter
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2095 Added my hilbert curve interpolation :)
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2096 Contribute a variant of the Hilbert Curve sketch
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2099 Driving a Car on an order 5 Hilbert Curve
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2100 "Image Rendering Curve"
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2102 Adding Community Contribution 9/10 for Hilbert Curve Video!
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2110 Add contribution to CC 103
  _CodingChallenges/103-fire-effect.md
Labels: Community Contribution

#2111 Update 003-hilbert-curve.md
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2112 Update 103-fire-effect.md
  _CodingChallenges/103-fire-effect.md
Labels: Community Contribution

#2113 Update 003-hilbert-curve.md
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2114 Update 003-hilbert-curve.md
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2121 Adding Workflow to Unit Testing
  unit_testing/files.js
  unit_testing/formats.js
  unit_testing/yaml.test.js
Labels: Unit Testing, Website

#2123 Added a refined UI for Daniels Snake game.
  _TeachableMachine/2-teachable-game.md
Labels: Community Contribution

#2124 001 starfield contribution : rainbow stars
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2126 Update 003-hilbert-curve.md
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2129 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2120 Adding Frequently Asked Questions
  _jekyll/includes/2-base/navigation.html
  _jekyll/layouts/faq.html
  _more/faq/index.md
  assets/css/3-layouts/_faq.sass
  assets/css/main.sass
  unit_testing/files.js
  unit_testing/formats.js
  unit_testing/yaml.test.js
Labels: Website

#2128 Add port to p5.js of Coding Challenge 8: Solar System part 2 (3D)
  CodingChallenges/CC_008_SolarSystemGenerator3D/P5/Planet.js
  CodingChallenges/CC_008_SolarSystemGenerator3D/P5/index.html
  CodingChallenges/CC_008_SolarSystemGenerator3D/P5/sketch.js
  _CodingChallenges/008-solarsystemgenerator3d.md
Labels: Code Portation (p5.js/Processing)

#2132 Add port to p5.js of CC 9: Solar System Generator part 3 (3D textures).
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/Planet.js
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/data/earth.jpg
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/data/mars.jpg
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/data/mercury.jpg
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/data/sun.jpg
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/index.html
  CodingChallenges/CC_009_SolarSystemGenerator3D_texture/P5/sketch.js
  _CodingChallenges/009-solarsystemgenerator3d-texture.md
Labels: Code Portation (p5.js/Processing)

#2133 Added more Vizualizations of Sorting algorithms
  _CodingChallenges/143-quicksort.md
Labels: Community Contribution

#2135 Fixing Repo Name for ml5 8.1
  learning/ml5/8.1_pixel_input/p5-multi/main/index.html
  learning/ml5/8.1_pixel_input/p5-multi/main/sketch.js
  learning/ml5/8.1_pixel_input/p5-multi/regression/index.html
  learning/ml5/8.1_pixel_input/p5-multi/regression/sketch.js
  learning/ml5/8.1_pixel_input/p5-multi/template/index.html
  learning/ml5/8.1_pixel_input/p5-multi/template/sketch.js
Labels: Website

#2136 Adding CNN Pages
  _learning/ml5/8.2-cnn-1.md
  _learning/ml5/8.3-cnn-2.md
  learning/ml5/8.2-cnn-1/P5/cat.png
  learning/ml5/8.2-cnn-1/P5/index.html
  learning/ml5/8.2-cnn-1/P5/sketch.js
  learning/ml5/8.3-cnn-2/P5/cat.png
  learning/ml5/8.3-cnn-2/P5/index.html
  learning/ml5/8.3-cnn-2/P5/sketch.js
Labels: New Pages

#2141 BFS Visualization Contribution
  _CodingChallenges/068.1-bfs-kevin-bacon.md
Labels: Community Contribution

#2144 Add a port to p5.js of Coding Challenge 58: 3D Earthquake Visualization
  CodingChallenges/CC_058_EarthQuakeViz3D/P5/earth.jpg
  CodingChallenges/CC_058_EarthQuakeViz3D/P5/index.html
  CodingChallenges/CC_058_EarthQuakeViz3D/P5/sketch.js
  CodingChallenges/CC_058_EarthQuakeViz3D/Processing/CC_058_EarthQuakeViz3D/CC_058_EarthQuakeViz3D.pde
  _CodingChallenges/058-earthquakeviz3d.md
Labels: Code Portation (p5.js/Processing)

#2146 Add a port to p5.js of Coding Challenge 101: May the 4th Scrolling Text
  CodingChallenges/CC_101_MayThe4th/P5/AvenirNextLTPro-Demi.otf
  CodingChallenges/CC_101_MayThe4th/P5/index.html
  CodingChallenges/CC_101_MayThe4th/P5/sketch.js
  CodingChallenges/CC_101_MayThe4th/P5/space.txt
Labels: Code Portation (p5.js/Processing)

#2147 Add Flappy Pose to Flappy Bird community contribs
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution
