Repository CodingTrain/website, pull requests merged in 2020-04, with the labels that each got.

#2200 Fixing Web Editor API
  _learning/nature-of-code/2.2-mass-acceleration.md
  unit_testing/yaml.test.js
Labels: CI

#2201 Space Invaders Contribution: Classic Space Invaders with p5.js
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution

#2204 User contribution - Exponential mitosis growth
  _CodingChallenges/006-mitosis-p5.md
Labels: Community Contribution

#2208 First p5.js rectangle face
  _beginners/p5js/1.1-introduction.md
Labels: Community Contribution

#2209 Moving objects
  _beginners/p5js/2.1-mousex-mousey.md
Labels: Community Contribution

#2203 Page for NOC 2.3
  _learning/nature-of-code/2.3-friction.md
  learning/nature-of-code/2.3_friction/P5/index.html
  learning/nature-of-code/2.3_friction/P5/mover.js
  learning/nature-of-code/2.3_friction/P5/sketch.js
Labels: New Pages

#2211 Update 003-hilbert-curve.md
  _CodingInTheCabana/003-hilbert-curve.md
Labels: Community Contribution

#2213 Bouncing ball with color changes
  _beginners/p5js/3.1-conditional-statements.md
Labels: Community Contribution

#2215 Update 2.1-transfer-learning.md
  _learning/ml5/2.1-transfer-learning.md
Labels: Community Contribution

#2223 Update 134.1-heart-curve.md
  _CodingChallenges/134.1-heart-curve.md
Labels: Community Contribution

#2222 Update 2.3-friction.md
  _learning/nature-of-code/2.3-friction.md
Labels: Community Contribution

#2216 Adding Contributions - Rodrigo Kulb
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2225 Adding my Contribution!
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2228 Clock Contribution
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2227 Update 030-phyllotaxis.md
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#2226 Update 065.1-binary-tree.md
  _CodingChallenges/065.1-binary-tree.md
Labels: Community Contribution

#2229 Added My Version of Asteroids Game
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#2230 Add sorting algorithms visualiser
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#2214 Adding page for NOC 2.4 Drag
  _learning/nature-of-code/2.4-drag.md
  learning/nature-of-code/2.4_drag/P5/index.html
  learning/nature-of-code/2.4_drag/P5/mover.js
  learning/nature-of-code/2.4_drag/P5/sketch.js
Labels: New Pages

#2231 Update 2.4-drag.md
  _learning/nature-of-code/2.4-drag.md
Labels: Community Contribution

#2232 Remastered with pictures space invaders
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution

#2234 Update 2.4-drag.md
  _learning/nature-of-code/2.4-drag.md
Labels: Community Contribution

#2235 Yet another boids implementation
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#2239 Update 7.1-posenet.md
  _learning/ml5/7.1-posenet.md
Labels: Community Contribution

#2240 FlappyBird contribution: flappybird lite
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2242 100.1 Contribution: Flappy Bird Lite - TensorFlow
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#2243 Improving CI
  .github/workflows/build-test.yml
  .github/workflows/nodejs.yml
  .github/workflows/ruby.yml
Labels: CI

#2238 Meteors - Asteroids game v. 0.3 by Jakub Kurdziel
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#2197 Correct the amount of neighbours cells have in 2D
  CodingChallenges/CC_132_FluidSimulation/Processing/CC_132_FluidSimulation/MoreFluid.pde
Labels: Enhancement

#2181 Add port to p5.js of Coding Challenge 142.1: Rubiks Cube 1
  CodingChallenges/CC_142_Rubiks_Cube_1/P5/Cubie.js
  CodingChallenges/CC_142_Rubiks_Cube_1/P5/index.html
  CodingChallenges/CC_142_Rubiks_Cube_1/P5/sketch.js
Labels: Code Portation (p5.js/Processing)

#2244 Flowfield contribution
  _CodingChallenges/024-perlinnoiseflowfield.md
Labels: Community Contribution

#2245 Add my Hexapod Robot Simulator Project
  _CodingChallenges/064.1-forward-kinematics.md
Labels: Community Contribution

#2247 Update 124-flocking-boids.md
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#2248 Add my python implementation
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2250 adding a contribution
  _CodingChallenges/063.1-unikitty-flag.md
Labels: Community Contribution

#2255 Community Contribution - first
  _CodingChallenges/008-solarsystemgenerator3d.md
Labels: Community Contribution

#2256 Update 131-bouncing-dvd-logo.md
  _CodingChallenges/131-bouncing-dvd-logo.md
Labels: Community Contribution

#2257 Update 004-purplerain.md
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#2252 Adding Page for Nature of Code 2.5
  _learning/nature-of-code/2.5-gravitational-attraction.md
  learning/nature-of-code/2.5_gravitiational_attraction/P5/attractor.js
  learning/nature-of-code/2.5_gravitiational_attraction/P5/index.html
  learning/nature-of-code/2.5_gravitiational_attraction/P5/mover.js
  learning/nature-of-code/2.5_gravitiational_attraction/P5/sketch.js
Labels: New Pages

#2258 Update 095-approximating-pi.md
  _CodingChallenges/095-approximating-pi.md
Labels: Community Contribution

#2260 Community Contribution - simple 3d solar system with textures
  _CodingChallenges/009-solarsystemgenerator3d-texture.md
Labels: Community Contribution

#2259 Add genetic algorithm written in Rust
  _CodingChallenges/035.1-tsp.md
Labels: Community Contribution

#2261 Pong contribution: by OOP
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2264 Update 014-fractaltree.md
  _CodingChallenges/014-fractaltree.md
Labels: Community Contribution

#2265 Update 135-gif-loop.md
  _CodingChallenges/135-gif-loop.md
Labels: Community Contribution

#2267 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2272 Update 030-phyllotaxis.md
  _CodingChallenges/030-phyllotaxis.md
Labels: Community Contribution

#2273 Update rainbow.txt.
  CodingChallenges/CC_037_diastic/P5/rainbow.txt
Labels: Community Contribution
