Repository CodingTrain/website, pull requests merged in 2020-05, with the labels that each got.

#2275 Kali Puja FireWorks
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2276 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2277 Update 111-animated-sprite.md
  _CodingChallenges/111-animated-sprite.md
Labels: Community Contribution

#2278 Update 114-bubble-sort.md
  _CodingChallenges/114-bubble-sort.md
Labels: Community Contribution

#2280 Update 117-seven-segment.md
  _CodingChallenges/117-seven-segment.md
Labels: Community Contribution

#2281 Adding contribution
  _Courses/data-and-apis/3.3-mapping-databse-entries.md
Labels: Community Contribution

#2284 Update 156-pi-digits.md
  _CodingChallenges/156-pi-digits.md
Labels: Community Contribution

#2286 Matrix Rain In Processing
  _GuestTutorials/004-emily-xie-matrix-digital-rain.md
Labels: Community Contribution

#2287 Adding a pong webcam reference
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2288 The Burning Ship fractal
  _CodingChallenges/021-mandelbrot-p5.md
Labels: Community Contribution

#2289 Emojis flocking
  _CodingChallenges/124-flocking-boids.md
Labels: Community Contribution

#2291 Added my simple version
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2282 Worley Noise - Coding in the Cabana Page
  CodingInTheCabana/Cabana_004_worley_noise/P5/index.html
  CodingInTheCabana/Cabana_004_worley_noise/P5/sketch.js
  CodingInTheCabana/Cabana_004_worley_noise/Processing/worley_noise_cabana/worley_noise_cabana.pde
  _CodingInTheCabana/004-worley-noise.md
Labels: New Pages

#2293 Add Worley Noise contrib - Alca
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2296 Update 004-worley-noise.md
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2298 Added few cool things!
  _CodingChallenges/002-mengersponge.md
Labels: Community Contribution

#2299 Update 004-worley-noise.md
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2302 fixed potential bug with a tag opening in new tab
  _jekyll/layouts/video.html
Labels: Fix, Website, bug

#2304 Worley Noise pixelated
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2305 fixed more a tag target bugs
  _jekyll/includes/3-modules/link-list.html
Labels: Fix, Website, bug

#2308 Add Greg Kreisman contribution
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2309 Added yet another version!
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#2312 Update 004-worley-noise.md with my Cell Division simulation
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2313 Community contribution Kobe L.
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2306 Update 107-sandpiles.md
  _CodingChallenges/107-sandpiles.md
Labels: Community Contribution

#2314 Animated Worley Noise in O(n^2)
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2315 The drops can be attracted by the mouse
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#2316 075-clock.md
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2318 My contribution
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2319 Link change
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#2320 Adding Community Contribution to Worley Noise
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2322 Update 057-mapping-earthquake-data.md
  _CodingChallenges/057-mapping-earthquake-data.md
Labels: Community Contribution

#2324 createGraphics contribution: moving numbers
  _beginners/p5js/2.1-mousex-mousey.md
Labels: Community Contribution

#2325 Added Starfield in Processing/Python by thienxxn
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2326 Update 095-approximating-pi.md
  _CodingChallenges/095-approximating-pi.md
Labels: Community Contribution

#2327 Added "Menger sponge via Processing/Python"
  _CodingChallenges/002-mengersponge.md
Labels: Community Contribution

#2329 add contribution to 1.1_what_is_a_vector
  _learning/nature-of-code/1.1-what-is-a-vector.md
Labels: Community Contribution

#2330 #1.2 using factory function contribution
  _learning/nature-of-code/1.2-vector-math.md
Labels: Community Contribution

#2331 Community Contribution - Animated Worley Noise
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2334 Contribution to Gravity Sim
  _learning/ml5/2.1-transfer-learning.md
Labels: Community Contribution

#2335 #1.3 random vectors contribution
  _learning/nature-of-code/1.3-random-vector.md
Labels: Community Contribution

#2336 Update 012-lorenzattractor.md
  _CodingChallenges/012-lorenzattractor.md
Labels: Community Contribution

#2338 Added my version of the coding challenge
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2339 10Print using JavaScript
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2343 Community Contribution - A* pathfinding
  _CodingChallenges/051.1-astar.md
Labels: Community Contribution

#2345 Update 096-visualizing-pi.md
  _CodingChallenges/096-visualizing-pi.md
Labels: Community Contribution

#2346 Perlin Noise Terrain contribution: p5.js version
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#2350 Update 004-worley-noise.md
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2351 Update 027-fireworks.md
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2352 Worley Noise contribution: Boids controlling the points
  _CodingInTheCabana/004-worley-noise.md
Labels: Community Contribution

#2353 Update 005-space-invaders-p5.md
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution
