Repository CodingTrain/website, pull requests merged in 2020-01, with the labels that each got.

#2028 Update 155-kaleidoscope-snowflake.md
  _CodingChallenges/155-kaleidoscope-snowflake.md
Labels: Community Contribution

#2029 RDP Line Simplification in Python with Matplotlib
  _CodingChallenges/152-rdp-algorithm.md
Labels: Community Contribution

#2032 Asteroids Plus
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#2031 Added Surface of Water / Taught Cloth Simulation
  _CodingChallenges/063.1-unikitty-flag.md
Labels: Community Contribution

#2033 Update 027-fireworks.md
  _CodingChallenges/027-fireworks.md
Labels: Community Contribution

#2035 add snowflake creator
  _CodingChallenges/155-kaleidoscope-snowflake.md
Labels: Community Contribution

#2034 Asteroid Field with more 3D depth
  _CodingChallenges/001-starfield.md
Labels: Community Contribution

#2038 10PRINT in Python Pygame
  _CodingChallenges/076-10print.md
Labels: Community Contribution

#2037 Fix for safari issue
  _jekyll/includes/2-base/navigation.html
  assets/css/2-base/_navigation.sass
  assets/javascript/functions.js
Labels: Fix, Website

#2042 Making Changes to video dropdown buttons
  _jekyll/includes/3-modules/code-variation-dropdown.html
  _jekyll/layouts/video.html
  assets/css/2-base/_footer.sass
  assets/css/2-base/_navigation.sass
  assets/css/3-layouts/_video.sass
Labels: WIP, Website, accessibility

#2045 Update 068.1-bfs-kevin-bacon.md
  _CodingChallenges/068.1-bfs-kevin-bacon.md
Labels: Community Contribution

#2048 Adding contribution from
  _CodingChallenges/069.1-steering-evolution.md
Labels: Community Contribution

#2054 ml5.js Contribution - Posenet: Near-sighted camera
  _Courses/ml5-beginners-guide/7.1-posenet.md
Labels: Community Contribution

#2051 Adding discord cta
  _config.yml
  assets/css/2-base/_landing-page.sass
  landing-page.html
Labels: Website

#2055 added tic tac toe with dom manipulation
  _CodingChallenges/149-tic-tac-toe.md
Labels: Community Contribution

#2058 Snake Game Contribution: AI learns to play
  _CodingChallenges/115-snake-game-redux.md
Labels: Community Contribution

#2061 Pixel sorting game with live picture
  _CodingChallenges/047-pixelsorting.md
Labels: Community Contribution

#2060 PoseNet Estimation : By doing squat to play the video as an incentive.
  _Courses/ml5-beginners-guide/7.1-posenet.md
Labels: Community Contribution

#2063 updated merch store link
  _config.yml
Labels: Website

#2070 First Websockets contribution
  _CodingChallenges/032.1-agar.md
Labels: Community Contribution

#2071 Focus Visible Fix
  assets/css/1-tools/_vars.sass
  assets/javascript/functions.js
Labels: Fix, accessibility

#2072 Discord Button Contrast Fix
  assets/css/2-base/_landing-page.sass
Labels: accessibility

#2075 rat in a maze program
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2078 created a path finding visualiser using bfs.
  _CodingChallenges/010.1-maze-dfs-p5.md
Labels: Community Contribution

#2079 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution
