Repository CodingTrain/website, pull requests merged in 2021-08, with the labels that each got.

#3296 Update 034-dla.md
  _CodingChallenges/034-dla.md
Labels: Community Contribution

#3298 🚀 Added my version
  _CodingChallenges/004-purplerain.md
Labels: Community Contribution

#3300 Suggested new contribution for metaballs challenge
  _CodingChallenges/028-metaballs.md
Labels: Community Contribution

#3301 Update 160-spring-forces.md
  _CodingChallenges/160-spring-forces.md
Labels: Community Contribution

#3304 Update 011-perlinnoiseterrain.md
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#3306 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#3308 Update 003-snake-game-p5.md
  _CodingChallenges/003-snake-game-p5.md
Labels: Community Contribution

#3309 Adding page for cc163
  CodingChallenges/CC_163_Bezier/basic-bezier/index.html
  CodingChallenges/CC_163_Bezier/basic-bezier/sketch.js
  CodingChallenges/CC_163_Bezier/bezier-editor/index.html
  CodingChallenges/CC_163_Bezier/bezier-editor/sketch.js
  CodingChallenges/CC_163_Bezier/bezier-formula/index.html
  CodingChallenges/CC_163_Bezier/bezier-formula/particle.js
  CodingChallenges/CC_163_Bezier/bezier-formula/sketch.js
  CodingChallenges/CC_163_Bezier/bezier-vertex/index.html
  CodingChallenges/CC_163_Bezier/bezier-vertex/sketch.js
  CodingChallenges/CC_163_Bezier/cardioid-bezier/index.html
  CodingChallenges/CC_163_Bezier/cardioid-bezier/sketch.js
  CodingChallenges/CC_163_Bezier/cubic/index.html
  CodingChallenges/CC_163_Bezier/cubic/particle.js
  CodingChallenges/CC_163_Bezier/cubic/sketch.js
  CodingChallenges/CC_163_Bezier/quadratic/index.html
  CodingChallenges/CC_163_Bezier/quadratic/sketch.js
  _CodingChallenges/163-bezier.md
Labels: New Pages

#3310 Suggested new contribution for Brownian Snowflake challenge
  _CodingChallenges/127-snowflake-brownian.md
Labels: Community Contribution

#3311 Update 163-bezier.md
  _CodingChallenges/163-bezier.md
Labels: Community Contribution

#3313 Update 163-bezier.md
  _CodingChallenges/163-bezier.md
Labels: Community Contribution

#3315 Bezier Curve LERP Animations (2-10 points)
  _CodingChallenges/163-bezier.md
Labels: Community Contribution

#3316 Ported ClappingBird to Processing4
  CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/Bird.pde
  CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/CC_041_ClappyBird.pde
  CodingChallenges/CC_041_ClappyBird/Processing/CC_041_ClappyBird/Pipe.pde
Labels: Code Portation (p5.js/Processing)

#3318 BezierArt
  _CodingChallenges/163-bezier.md
Labels: Community Contribution

#3319 Update 125-fourier-series.md
  _CodingChallenges/125-fourier-series.md
Labels: Community Contribution

#3326 Bézier curve contribution: animated n point Bézier
  _CodingChallenges/163-bezier.md
Labels: Community Contribution
