Repository CodingTrain/website, pull requests merged in 2021-01, with the labels that each got.

#2973 Update 067-pong.md
  _CodingChallenges/067-pong.md
Labels: Community Contribution

#2979 Flappy Bird contribution: Batman themed graphics.
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2980 updated with animation
  _CodingChallenges/147-chrome-dinosaur.md
Labels: Community Contribution

#2955 SimplePerceptron in P5
  CodingChallenges/SimplePerceptron/P5/SimplePerceptron/index.html
  CodingChallenges/SimplePerceptron/P5/SimplePerceptron/perceptron.js
  CodingChallenges/SimplePerceptron/P5/SimplePerceptron/sketch.js
  CodingChallenges/SimplePerceptron/P5/SimplePerceptron/training.js
  CodingChallenges/SimplePerceptron/Processing/SimplePerceptron/Perceptron.pde
  CodingChallenges/SimplePerceptron/Processing/SimplePerceptron/SimplePerceptron.pde
  CodingChallenges/SimplePerceptron/Processing/SimplePerceptron/Training.pde
Labels: Code Portation (p5.js/Processing)

#2989 Update 071-minesweeper.md
  _CodingChallenges/071-minesweeper.md
Labels: Community Contribution

#2990 sandpiles contribution in P5
  _CodingChallenges/107-sandpiles.md
Labels: Community Contribution

#2991 Adding my 2021 contribution
  _CodingChallenges/088-snowfall.md
Labels: Community Contribution

#2995 Adding Contribution - Rings and Rings
  _CodingChallenges/036-blobby.md
Labels: Community Contribution

#2996 Clock Contribution Submission
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#2997 Update 031-flappybird.md
  _CodingChallenges/031-flappybird.md
Labels: Community Contribution

#2998 Page for Discord Command Handler Video
  _learning/bots/discord/06-command-handler.md
  learning/bots/discord/06-command-handler/Node/.env-sample
  learning/bots/discord/06-command-handler/Node/bot.js
  learning/bots/discord/06-command-handler/Node/commands.js
  learning/bots/discord/06-command-handler/Node/commands/choochoo.js
  learning/bots/discord/06-command-handler/Node/commands/gif.js
  learning/bots/discord/06-command-handler/Node/package-lock.json
  learning/bots/discord/06-command-handler/Node/package.json
Labels: New Pages

#2999 Blob White Rose
  _CodingChallenges/036-blobby.md
Labels: Community Contribution

#3000 Update 046.1-asteroids-part-1.md
  _CodingChallenges/046.1-asteroids-part-1.md
Labels: Community Contribution

#3002 Add Neural Network project
  _CodingChallenges/158-shape-classifier.md
Labels: Community Contribution

#3004 Pine fractal tree creator
  _CodingChallenges/014-fractaltree.md
Labels: Community Contribution

#3009 Adding Pages for Perlin Noise Playlist 0.2 - 0.5
  _jekyll/includes/2-base/navigation.html
  _learning/noise/0.2-inroduction.md
  _learning/noise/0.3-noise-vs-random.md
  _learning/noise/0.4-graphing-1d.md
  _learning/noise/0.5-2d-noise.md
  _learning/noise/index.md
  learning/noise/0.3-noise-vs-random/P5/index.html
  learning/noise/0.3-noise-vs-random/P5/sketch.js
  learning/noise/0.4-graphing-1d/noise-graph/index.html
  learning/noise/0.4-graphing-1d/noise-graph/sketch.js
  learning/noise/0.4-graphing-1d/noisy-sin/index.html
  learning/noise/0.4-graphing-1d/noisy-sin/sketch.js
  learning/noise/0.4-graphing-1d/y-axis/index.html
  learning/noise/0.4-graphing-1d/y-axis/sketch.js
  learning/noise/0.5-2d-noise/P5/index.html
  learning/noise/0.5-2d-noise/P5/sketch.js
Labels: New Pages

#3011 Adding page for NOC 3.1 video
  _learning/nature-of-code/3.1-angles-rotation.md
  learning/nature-of-code/3.1-angles-rotation/P5/index.html
  learning/nature-of-code/3.1-angles-rotation/P5/sketch.js
Labels: New Pages

#3013 Adding Page for NOC 3.2
  _learning/nature-of-code/3.2-anglular-motion.md
  _learning/nature-of-code/index.md
  learning/nature-of-code/3.2-angular-motion/grab/index.html
  learning/nature-of-code/3.2-angular-motion/grab/sketch.js
  learning/nature-of-code/3.2-angular-motion/gravitational-attraction/attractor.js
  learning/nature-of-code/3.2-angular-motion/gravitational-attraction/index.html
  learning/nature-of-code/3.2-angular-motion/gravitational-attraction/mover.js
  learning/nature-of-code/3.2-angular-motion/gravitational-attraction/sketch.js
  learning/nature-of-code/3.2-angular-motion/rect-acc/index.html
  learning/nature-of-code/3.2-angular-motion/rect-acc/sketch.js
Labels: New Pages

#3015 new contribution to hypercube challenge
  _CodingChallenges/113-hypercube.md
Labels: Community Contribution

#3016 01-perlinnoiseterrain contribution: add an extra field for tunnel effect
  _CodingChallenges/011-perlinnoiseterrain.md
Labels: Community Contribution

#3017 Update 085-the-game-of-life.md
  _CodingChallenges/085-the-game-of-life.md
Labels: Community Contribution
