Repository CodingTrain/website, pull requests merged in 2021-02, with the labels that each got.

#3020 Adding page for NOC 3.3
  _learning/nature-of-code/3.3-angles-and-vectors.md
  learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/index.html
  learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/sketch.js
  learning/nature-of-code/3.3-angles-and-vectors/asteroids-exercise/spaceship.js
  learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/attractor.js
  learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/index.html
  learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/mover.js
  learning/nature-of-code/3.3-angles-and-vectors/direction-pointing/sketch.js
  learning/nature-of-code/3.3-angles-and-vectors/vehicle/index.html
  learning/nature-of-code/3.3-angles-and-vectors/vehicle/mover.js
  learning/nature-of-code/3.3-angles-and-vectors/vehicle/sketch.js
Labels: New Pages

#3021 Nature of Code 3.3 - communitiy contribution
  _learning/nature-of-code/3.3-angles-and-vectors.md
Labels: Community Contribution

#3024 Using a new caching key for ruby jobs to resolve #3022
  .github/workflows/build.yml
  .github/workflows/featurepeek.yml
Labels: CI, Fix

#3025 Nature of Code 3.3 - Community contribution
  _learning/nature-of-code/3.3-angles-and-vectors.md
Labels: Community Contribution

#3026 Chaos game! Sierpinski Tetrahedron
  _CodingChallenges/123.1-chaos-game.md
Labels: Community Contribution

#3027 Neuroevolution Contribution: NEAT library
  _CodingChallenges/100.1-neuroevolution-flappy-bird.md
Labels: Community Contribution

#3028 Nature of Code 3.1 - Community contribution
  _learning/nature-of-code/3.1-angles-rotation.md
Labels: Community Contribution

#3029 Adding page for NOC 3.4
  _learning/nature-of-code/3.4-polar-coordinates.md
  learning/nature-of-code/3.4-polar-coordinates/basic-polar-coordinates/index.html
  learning/nature-of-code/3.4-polar-coordinates/basic-polar-coordinates/sketch.js
  learning/nature-of-code/3.4-polar-coordinates/circular-shape/index.html
  learning/nature-of-code/3.4-polar-coordinates/circular-shape/sketch.js
  learning/nature-of-code/3.4-polar-coordinates/random-trail/index.html
  learning/nature-of-code/3.4-polar-coordinates/random-trail/sketch.js
  learning/nature-of-code/3.4-polar-coordinates/spiral/index.html
  learning/nature-of-code/3.4-polar-coordinates/spiral/sketch.js
Labels: New Pages

#3030 Minimax Algorithm Contribution: Chess AI in js
  _CodingChallenges/154-tic-tac-toe-minimax.md
Labels: Community Contribution

#3031 Ported it over to Roblox
  _CodingChallenges/086-beesandbombs.md
Labels: Community Contribution

#3032 Noc 3.5
  _learning/nature-of-code/3.5-simple-harmonic-motion.md
  learning/nature-of-code/3.5-simple-harmonic-motion/2-axes-exercise/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/2-axes-exercise/sketch.js
  learning/nature-of-code/3.5-simple-harmonic-motion/approximate-time/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/approximate-time/sketch.js
  learning/nature-of-code/3.5-simple-harmonic-motion/basic/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/basic/sketch.js
  learning/nature-of-code/3.5-simple-harmonic-motion/exact-time-exercise/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/exact-time-exercise/sketch.js
  learning/nature-of-code/3.5-simple-harmonic-motion/main/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/main/sketch.js
  learning/nature-of-code/3.5-simple-harmonic-motion/yoyo/index.html
  learning/nature-of-code/3.5-simple-harmonic-motion/yoyo/sketch.js
Labels: New Pages

#3033 Nature of Code 3.4 Contribution: Rainbow Spiral
  _learning/nature-of-code/3.4-polar-coordinates.md
Labels: Community Contribution

#3034 Update 2.5-gravitational-attraction.md
  _learning/nature-of-code/2.5-gravitational-attraction.md
Labels: Community Contribution

#3037 Community Contribution
  _learning/nature-of-code/3.5-simple-harmonic-motion.md
Labels: Community Contribution

#3039 YouTube descriptions generator improvements
  .gitignore
  _scripts/generate-youtube-descriptions.js
Labels: Repository, YouTube

#3036 Doodler with Color Options
  _beginners/p5js/2.1-mousex-mousey.md
Labels: Community Contribution

#3038 Adding page for NOC 3.6
  _learning/nature-of-code/3.6-graphing-sine.md
  learning/nature-of-code/3.6-graphing-sine/circular-wave-exercise/index.html
  learning/nature-of-code/3.6-graphing-sine/circular-wave-exercise/sketch.js
  learning/nature-of-code/3.6-graphing-sine/graphing-wave/index.html
  learning/nature-of-code/3.6-graphing-sine/graphing-wave/sketch.js
  learning/nature-of-code/3.6-graphing-sine/playing-with-period/index.html
  learning/nature-of-code/3.6-graphing-sine/playing-with-period/sketch.js
  learning/nature-of-code/3.6-graphing-sine/sine-wave-graph-exercise/index.html
  learning/nature-of-code/3.6-graphing-sine/sine-wave-graph-exercise/sketch.js
Labels: New Pages

#3040 Update 091.1-snakes-and-ladders.md
  _CodingChallenges/091.1-snakes-and-ladders.md
Labels: Community Contribution

#3046 Contribution: lots of movers and a moving attractor
  _learning/nature-of-code/2.2-mass-acceleration.md
Labels: Community Contribution

#3047 clock with colorful trails
  _learning/nature-of-code/3.4-polar-coordinates.md
Labels: Community Contribution

#3048 Clock with trails
  _CodingChallenges/074-clock.md
Labels: Community Contribution

#3049 Weird rainbow generator by Abhay and Simon!!
  _learning/nature-of-code/3.5-simple-harmonic-motion.md
Labels: Community Contribution

#3050 Adding Yoyo Craziness!!
  _learning/nature-of-code/3.5-simple-harmonic-motion.md
Labels: Community Contribution

#3052 Update 130.1-fourier-transform-drawing.md
  _CodingChallenges/130.1-fourier-transform-drawing.md
Labels: Community Contribution

#3055 Adding page for NOC 3.7
  _learning/nature-of-code/3.7-additive-waves.md
  learning/nature-of-code/3.7-additive-waves/P5/index.html
  learning/nature-of-code/3.7-additive-waves/P5/sketch.js
  learning/nature-of-code/3.7-additive-waves/P5/wave.js
Labels: New Pages

#3056 Adding some color full sine waves which has some sliders also!
  _learning/nature-of-code/3.7-additive-waves.md
Labels: Community Contribution

#3054 Adding Coding Challenge #42.1 in Processing for the Coding Train website
  CodingChallenges/CC_042.1_markov-chain/Processing/CC_042_1_markov-chain/CC_042_1_markov_chain/CC_042_1_markov_chain.pde
Labels: Code Portation (p5.js/Processing)

#3057 Ported CC_042_2_markov-chain-names to Processing
  CodingChallenges/CC_042.2_markov-chain-names/Processing/CC_042_2_markov-chain-names/CC_042_2_markov_chain_names/CC_042_2_markov_chain_names.pde
  CodingChallenges/CC_042.2_markov-chain-names/Processing/CC_042_2_markov-chain-names/CC_042_2_markov_chain_names/data/names.txt
Labels: Code Portation (p5.js/Processing)

#3059 3.7 Additive Waves contribution from FelixCPP
  _learning/nature-of-code/3.7-additive-waves.md
Labels: Community Contribution

#3060 add my contribution, made with ❤️
  _learning/nature-of-code/3.7-additive-waves.md
Labels: Community Contribution

#3061 Port CC_037_diastic to Processing
  CodingChallenges/CC_037_diastic/Processing/CC_037_diastic/CC_037_diastic/CC_037_diastic.pde
  CodingChallenges/CC_037_diastic/Processing/CC_037_diastic/CC_037_diastic/data/rainbow.txt
Labels: Code Portation (p5.js/Processing)

#3064 Adding page for coding challenge 159
  .eslintignore
  CodingChallenges/CC_159_simple_pendulum_simulation/P5/index.html
  CodingChallenges/CC_159_simple_pendulum_simulation/P5/sketch.js
  CodingChallenges/CC_159_simple_pendulum_simulation/Processing/cc_159_simple_pendulum_simulation/cc_159_simple_pendulum_simulation.pde
  _CodingChallenges/159-simple-pendulum-simulation.md
  _CodingChallenges/index.md
  _learning/nature-of-code/3.2-angular-motion.md
  _learning/nature-of-code/3.7-additive-waves.md
Labels: Code Portation (p5.js/Processing), New Pages

#3066 Contribution: pendulum on a cart
  _CodingChallenges/159-simple-pendulum-simulation.md
Labels: Community Contribution

#3067 Added community contribution
  _CodingChallenges/159-simple-pendulum-simulation.md
Labels: Community Contribution

#3069 Colourful Pendulum
  _CodingChallenges/159-simple-pendulum-simulation.md
Labels: Community Contribution

#3072 Adding page for CC160
  CodingChallenges/CC_160_spring_forces/simple-spring-port/cc160_simple_spring_port/cc160_simple_spring_port.pde
  CodingChallenges/CC_160_spring_forces/simple-spring/index.html
  CodingChallenges/CC_160_spring_forces/simple-spring/sketch.js
  CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/Particle.pde
  CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/Spring.pde
  CodingChallenges/CC_160_spring_forces/soft-spring-port/cc160_soft_spring_port/cc160_soft_spring_port.pde
  CodingChallenges/CC_160_spring_forces/soft-spring/index.html
  CodingChallenges/CC_160_spring_forces/soft-spring/particle.js
  CodingChallenges/CC_160_spring_forces/soft-spring/sketch.js
  CodingChallenges/CC_160_spring_forces/soft-spring/spring.js
  CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/Particle.pde
  CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/Spring.pde
  CodingChallenges/CC_160_spring_forces/spring-oop-port/cc160_spring_oop_port/cc160_spring_oop_port.pde
  CodingChallenges/CC_160_spring_forces/spring-oop/index.html
  CodingChallenges/CC_160_spring_forces/spring-oop/particle.js
  CodingChallenges/CC_160_spring_forces/spring-oop/sketch.js
  CodingChallenges/CC_160_spring_forces/spring-oop/spring.js
  CodingChallenges/CC_160_spring_forces/spring-vector-port/cc160_spring_vector_port/cc160_spring_vector_port.pde
  CodingChallenges/CC_160_spring_forces/spring-vector/index.html
  CodingChallenges/CC_160_spring_forces/spring-vector/sketch.js
  _CodingChallenges/160-spring-forces.md
Labels: Code Portation (p5.js/Processing), New Pages

#3075 Update 091.1-snakes-and-ladders.md
  _CodingChallenges/091.1-snakes-and-ladders.md
Labels: Community Contribution

#3076 Adding contribution: "Grab Any Spring Particle"
  _CodingChallenges/160-spring-forces.md
Labels: Community Contribution

#3077 Pendulum Contribution: Up Down Left Right
  _CodingChallenges/159-simple-pendulum-simulation.md
Labels: Community Contribution

#3079 Removing the Patreon reference from the supporting section
  landing-page.html
Labels: Website

#3080 pendulum website
  _CodingChallenges/159-simple-pendulum-simulation.md
Labels: Community Contribution

#3081 Spring Force Contribution - Grass
  _CodingChallenges/160-spring-forces.md
Labels: Community Contribution

#3083 Mistake Are Beautiful
  _CodingChallenges/160-spring-forces.md
Labels: Community Contribution

#3084 Adding my contribution
  _learning/ml5/6.1-train-your-own.md
Labels: Community Contribution

#3085 Update 7.1-posenet.md
  _learning/ml5/7.1-posenet.md
Labels: Community Contribution

#3086 Community Contribution
  _CodingChallenges/005-space-invaders-p5.md
Labels: Community Contribution
